/*
===========================================================================
cl_character_cod1.c  --  Client-side CoD1 third-person character rendering

Draws a CoD-style xmodel for the local player when cg_thirdPerson is enabled.
Model source:
  1) cl_thirdPersonModel (explicit xmodel path or short name)
  2) character script (cl_thirdPersonCharacter, parsed for setModel/attach)

Animation source:
  CoD MP locomotion xanims (pb_*), selected from playerState legs/torso anim
  state + movement direction.
===========================================================================
*/
#include "client.h"

#ifdef STANDALONE

#include <math.h>
#include <stdlib.h>
#include "../thirdparty/gsc/include/gsc.h"

#define TP_MAX_ATTACHMENTS 32
#define TP_TAGNAME_LEN     64

typedef enum {
    TP_LEG_ANIM_STAND_IDLE = 0,
    TP_LEG_ANIM_STAND_FWD,
    TP_LEG_ANIM_STAND_BACK,
    TP_LEG_ANIM_STAND_LEFT,
    TP_LEG_ANIM_STAND_RIGHT,
    TP_LEG_ANIM_CROUCH_IDLE,
    TP_LEG_ANIM_CROUCH_FWD,
    TP_LEG_ANIM_CROUCH_BACK,
    TP_LEG_ANIM_CROUCH_LEFT,
    TP_LEG_ANIM_CROUCH_RIGHT,
    TP_LEG_ANIM_PRONE_IDLE,
    TP_LEG_ANIM_PRONE_FWD,
    TP_LEG_ANIM_PRONE_BACK,
    TP_LEG_ANIM_PRONE_LEFT,
    TP_LEG_ANIM_PRONE_RIGHT,
    TP_LEG_ANIM_COUNT
} tpLegAnimSlot_t;

typedef enum {
    TP_TORSO_ANIM_STAND_IDLE = 0,
    TP_TORSO_ANIM_STAND_FIRE,
    TP_TORSO_ANIM_CROUCH_IDLE,
    TP_TORSO_ANIM_CROUCH_FIRE,
    TP_TORSO_ANIM_PRONE_IDLE,
    TP_TORSO_ANIM_PRONE_FIRE,
    TP_TORSO_ANIM_COUNT
} tpTorsoAnimSlot_t;

static const char *s_tpLegAnimNames[TP_LEG_ANIM_COUNT] = {
    "pb_stand_alert",
    "pb_stand_shoot_walk_forward",
    "pb_stand_shoot_walk_back",
    "pb_stand_shoot_walk_left",
    "pb_stand_shoot_walk_right",
    "pb_crouch_alert",
    "pb_crouch_run_forward",
    "pb_crouch_run_back",
    "pb_crouch_run_left",
    "pb_crouch_run_right",
    "pb_prone_aim",
    "pb_prone_crawl",
    "pb_prone_crawl_back",
    "pb_prone_crawl_left",
    "pb_prone_crawl_right"
};

static const char *s_tpTorsoAnimCandidates[TP_TORSO_ANIM_COUNT][4] = {
    { "pt_stand_pullout_pose", "pt_stand_shoot_ads", "pt_stand_shoot", NULL },
    { "pt_stand_shoot_auto",   "pt_stand_shoot",     "pt_rifle_fire",  NULL },
    { "pt_crouch_pullout_pose","pt_crouch_shoot_ads","pt_crouch_shoot",NULL },
    { "pt_crouch_shoot_auto",  "pt_crouch_shoot",    NULL,             NULL },
    { "pt_prone_pullout_pose", "pt_prone_shoot",     NULL,             NULL },
    { "pt_prone_shoot_auto",   "pt_prone_shoot",     NULL,             NULL }
};

typedef struct {
    char      modelPath[MAX_QPATH];
    char      tagName[TP_TAGNAME_LEN];
    qhandle_t hModel;
} tpAttachment_t;

typedef struct {
    qhandle_t      baseModel;
    qhandle_t      legAnims[TP_LEG_ANIM_COUNT];
    qhandle_t      torsoAnims[TP_TORSO_ANIM_COUNT];
    tpAttachment_t attachments[TP_MAX_ATTACHMENTS];
    int            numAttachments;

    char           loadedModelPath[MAX_QPATH];
    char           loadedScriptPath[MAX_QPATH];
    char           loadedModelOverride[MAX_QPATH];

    tpLegAnimSlot_t   currentLegAnim;
    tpTorsoAnimSlot_t currentTorsoAnim;
    int               legAnimStartTime;
    int               torsoAnimStartTime;
    float          renderYaw;
    qboolean       renderYawValid;
} tpCharacterState_t;

static tpCharacterState_t s_tpChar;

/* cvars */
static cvar_t *cl_drawThirdPersonCharacter;
static cvar_t *cl_thirdPersonCharacter;
static cvar_t *cl_thirdPersonModel;
static cvar_t *cl_thirdPersonYawOffset;
static cvar_t *cl_thirdPersonPitchScale;
static cvar_t *cl_thirdPersonZOffset;
static cvar_t *cl_thirdPersonAnimRate;
static cvar_t *cl_thirdPersonMoveThreshold;
static cvar_t *cl_thirdPersonFaceView;
static cvar_t *cl_thirdPersonFaceMove;
static cvar_t *cl_thirdPersonUseGsc;
static cvar_t *cl_thirdPersonBlendTorso;
static cvar_t *cl_thirdPersonTorsoRoot;
static cvar_t *cl_thirdPersonYawLerpSpeed;
static cvar_t *cl_thirdPersonDebug;

static qhandle_t CL_TP_RegisterModelWithFallback( const char *requestedPath,
                                                  char *resolvedPath,
                                                  int resolvedPathSize )
{
    qhandle_t hModel;
    int i;
    const char *fallbacks[] = {
        "xmodel/playerbody_german_wehrmacht",
        "xmodel/playerbody_american_airborne",
        "xmodel/playerbody_russian_veteran",
        "xmodel/playerbody_default"
    };

    if ( !requestedPath || !requestedPath[0] ) {
        resolvedPath[0] = '\0';
        return 0;
    }

    hModel = re.RegisterModel( requestedPath );
    if ( hModel ) {
        Q_strncpyz( resolvedPath, requestedPath, resolvedPathSize );
        return hModel;
    }

    /* CoD1 MP's autogenerated mp_axis_default.gsc references this alias.
     * Prefer a non-placeholder body first to avoid default white fallback. */
    if ( !Q_stricmp( requestedPath, "xmodel/axis_default" ) ) {
        hModel = re.RegisterModel( "xmodel/playerbody_german_wehrmacht" );
        if ( hModel ) {
            Q_strncpyz( resolvedPath, "xmodel/playerbody_german_wehrmacht", resolvedPathSize );
            return hModel;
        }
    }

    for ( i = 0; i < (int)ARRAY_LEN( fallbacks ); ++i ) {
        if ( !Q_stricmp( requestedPath, fallbacks[i] ) ) {
            continue;
        }

        hModel = re.RegisterModel( fallbacks[i] );
        if ( hModel ) {
            Q_strncpyz( resolvedPath, fallbacks[i], resolvedPathSize );
            return hModel;
        }
    }

    Q_strncpyz( resolvedPath, requestedPath, resolvedPathSize );
    return 0;
}

static void CL_TP_NormalizeModelPath( const char *input, char *out, int outSize )
{
    if ( !input || !input[0] ) {
        out[0] = '\0';
        return;
    }

    if ( Q_strncmp( input, "xmodel/", 7 ) == 0 ) {
        Q_strncpyz( out, input, outSize );
    } else {
        Com_sprintf( out, outSize, "xmodel/%s", input );
    }
}

static void CL_TP_BuildCharacterScriptPath( const char *name, char *outPath, int outSize )
{
    const char *base;

    base = ( name && name[0] ) ? name : "mp_axis_default";

    if ( Q_strncmp( base, "character/", 10 ) == 0 ) {
        Q_strncpyz( outPath, base, outSize );
    } else {
        Com_sprintf( outPath, outSize, "character/%s", base );
    }

    if ( !COM_GetExtension( outPath )[0] ) {
        Q_strcat( outPath, outSize, ".gsc" );
    }
}

static qboolean CL_TP_ParseQuoted( const char *start, const char **after, char *out, int outSize )
{
    const char *open;
    const char *close;
    int len;

    open = strchr( start, '"' );
    if ( !open ) {
        return qfalse;
    }

    close = strchr( open + 1, '"' );
    if ( !close ) {
        return qfalse;
    }

    len = (int)( close - ( open + 1 ) );
    if ( len >= outSize ) {
        len = outSize - 1;
    }

    if ( len > 0 ) {
        memcpy( out, open + 1, len );
    }
    out[len] = '\0';

    if ( after ) {
        *after = close + 1;
    }

    return qtrue;
}

static qboolean CL_TP_IsAliasChar( char c )
{
    return ( ( c >= 'a' && c <= 'z' ) ||
             ( c >= 'A' && c <= 'Z' ) ||
             ( c >= '0' && c <= '9' ) ||
             c == '_' );
}

static qboolean CL_TP_ParseAliasName( const char *text, char *outAlias, int outAliasSize )
{
    const char *marker;
    int i;

    marker = Q_stristr( text, "xmodelalias\\" );
    if ( !marker ) {
        marker = Q_stristr( text, "xmodelalias/" );
    }
    if ( !marker ) {
        return qfalse;
    }

    marker += 11; /* strlen("xmodelalias/") */
    i = 0;
    while ( marker[i] && CL_TP_IsAliasChar( marker[i] ) ) {
        if ( i >= outAliasSize - 1 ) {
            break;
        }
        outAlias[i] = marker[i];
        i++;
    }

    if ( i <= 0 ) {
        return qfalse;
    }

    outAlias[i] = '\0';
    return qtrue;
}

static qboolean CL_TP_ResolveAliasToModel( const char *text, char *outModelPath, int outModelPathSize )
{
    char aliasName[MAX_QPATH];
    char aliasPath[MAX_QPATH];
    char *aliasText;
    long aliasLen;
    const char *scan;

    outModelPath[0] = '\0';

    if ( !CL_TP_ParseAliasName( text, aliasName, sizeof( aliasName ) ) ) {
        return qfalse;
    }

    Com_sprintf( aliasPath, sizeof( aliasPath ), "xmodelalias/%s.gsc", aliasName );
    aliasText = NULL;
    aliasLen = FS_ReadFile( aliasPath, (void **)&aliasText );
    if ( aliasLen <= 0 || !aliasText ) {
        return qfalse;
    }

    scan = aliasText;
    while ( CL_TP_ParseQuoted( scan, &scan, outModelPath, outModelPathSize ) ) {
        if ( outModelPath[0] ) {
            CL_TP_NormalizeModelPath( outModelPath, outModelPath, outModelPathSize );
            FS_FreeFile( aliasText );
            return qtrue;
        }
    }

    FS_FreeFile( aliasText );
    outModelPath[0] = '\0';
    return qfalse;
}

static qboolean CL_TP_IsHeadLikeModel( const char *modelPath )
{
    return modelPath && (
        Q_stristr( modelPath, "basehead" ) ||
        Q_stristr( modelPath, "head_" ) ||
        Q_stristr( modelPath, "/head" ) ||
        Q_stristr( modelPath, "headaxis" )
    );
}

static qboolean CL_TP_IsHelmetLikeModel( const char *modelPath )
{
    return modelPath && (
        Q_stristr( modelPath, "helmet" ) ||
        Q_stristr( modelPath, "_hat" ) ||
        Q_stristr( modelPath, "hat_" ) ||
        Q_stristr( modelPath, "sidecap" ) ||
        Q_stristr( modelPath, "officercap" ) ||
        Q_stristr( modelPath, "_cap" ) ||
        Q_stristr( modelPath, "cap_" )
    );
}

static const char *CL_TP_DefaultTagForAttachment( const char *modelPath )
{
    if ( CL_TP_IsHeadLikeModel( modelPath ) ) {
        return "bip01 spine2";
    }

    if ( CL_TP_IsHelmetLikeModel( modelPath ) ) {
        return "tag_helmet";
    }

    return "";
}

static void CL_TP_AddAttachment( tpAttachment_t *attachments, int *numAttachments,
                                 const char *modelPath, const char *tagName )
{
    int i;

    if ( !modelPath || !modelPath[0] ) {
        return;
    }

    for ( i = 0; i < *numAttachments; ++i ) {
        if ( !Q_stricmp( attachments[i].modelPath, modelPath ) &&
             !Q_stricmp( attachments[i].tagName, tagName ? tagName : "" ) ) {
            return;
        }
    }

    if ( *numAttachments >= TP_MAX_ATTACHMENTS ) {
        return;
    }

    Q_strncpyz( attachments[*numAttachments].modelPath, modelPath,
                sizeof( attachments[*numAttachments].modelPath ) );
    Q_strncpyz( attachments[*numAttachments].tagName,
                tagName ? tagName : "",
                sizeof( attachments[*numAttachments].tagName ) );
    attachments[*numAttachments].hModel = 0;
    ( *numAttachments )++;
}

typedef struct {
    char          baseModel[MAX_QPATH];
    char          viewModel[MAX_QPATH];
    tpAttachment_t attachments[TP_MAX_ATTACHMENTS];
    int           numAttachments;
    unsigned int  randState;
    char         *loadedSources[256];
    int           numLoadedSources;
} tpGscEvalState_t;

static tpGscEvalState_t *s_tpGscEval;

static void CL_TP_GscNormalizePath( const char *in, char *out, int outSize )
{
    int i;

    if ( !in || !in[0] ) {
        out[0] = '\0';
        return;
    }

    Q_strncpyz( out, in, outSize );
    for ( i = 0; out[i]; ++i ) {
        if ( out[i] == '\\' ) {
            out[i] = '/';
        }
    }
}

static void CL_TP_GscBuildSourcePath( const char *name, char *outPath, int outPathSize )
{
    CL_TP_GscNormalizePath( name, outPath, outPathSize );
    if ( !COM_GetExtension( outPath )[0] ) {
        Q_strcat( outPath, outPathSize, ".gsc" );
    }
}

static void CL_TP_GscBuildNamespace( const char *name, char *outNamespace, int outNamespaceSize )
{
    CL_TP_GscNormalizePath( name, outNamespace, outNamespaceSize );
    COM_StripExtension( outNamespace, outNamespace, outNamespaceSize );
}

static unsigned int CL_TP_GscNextRand( void )
{
    if ( !s_tpGscEval ) {
        return 0;
    }

    if ( !s_tpGscEval->randState ) {
        s_tpGscEval->randState = 0xC001D00Du;
    }

    s_tpGscEval->randState ^= s_tpGscEval->randState << 13;
    s_tpGscEval->randState ^= s_tpGscEval->randState >> 17;
    s_tpGscEval->randState ^= s_tpGscEval->randState << 5;
    return s_tpGscEval->randState;
}

static void CL_TP_GscTrackSource( char *source )
{
    if ( !s_tpGscEval || !source ) {
        return;
    }

    if ( s_tpGscEval->numLoadedSources >= (int)ARRAY_LEN( s_tpGscEval->loadedSources ) ) {
        free( source );
        return;
    }

    s_tpGscEval->loadedSources[s_tpGscEval->numLoadedSources++] = source;
}

static void CL_TP_GscFreeTrackedSources( tpGscEvalState_t *state )
{
    int i;

    if ( !state ) {
        return;
    }

    for ( i = 0; i < state->numLoadedSources; ++i ) {
        free( state->loadedSources[i] );
        state->loadedSources[i] = NULL;
    }
    state->numLoadedSources = 0;
}

static void *CL_TP_GscAllocMemory( void *ctx, int size )
{
    (void)ctx;
    return calloc( 1, (size_t)( size > 0 ? size : 1 ) );
}

static void CL_TP_GscFreeMemory( void *ctx, void *ptr )
{
    (void)ctx;
    free( ptr );
}

static const char *CL_TP_GscReadFile( void *ctx, const char *filename, int *status )
{
    char sourcePath[MAX_QPATH];
    char *fileText;
    long fileLen;
    char *copy;

    (void)ctx;

    CL_TP_GscBuildSourcePath( filename, sourcePath, sizeof( sourcePath ) );

    fileText = NULL;
    fileLen = FS_ReadFile( sourcePath, (void **)&fileText );
    if ( fileLen <= 0 || !fileText ) {
        *status = GSC_NOT_FOUND;
        return NULL;
    }

    copy = (char *)malloc( (size_t)fileLen + 1 );
    if ( !copy ) {
        FS_FreeFile( fileText );
        *status = GSC_OUT_OF_MEMORY;
        return NULL;
    }

    if ( fileLen > 0 ) {
        memcpy( copy, fileText, (size_t)fileLen );
    }
    copy[fileLen] = '\0';

    FS_FreeFile( fileText );
    CL_TP_GscTrackSource( copy );
    *status = GSC_OK;
    return copy;
}

static int CL_TP_GscFn_IsDefined( gsc_Context *ctx )
{
    gsc_add_bool( ctx, gsc_get_type( ctx, 0 ) != GSC_TYPE_UNDEFINED );
    return 1;
}

static int CL_TP_GscFn_RandomInt( gsc_Context *ctx )
{
    int maxVal;
    unsigned int r;

    maxVal = (int)gsc_get_int( ctx, 0 );
    if ( maxVal <= 0 ) {
        gsc_add_int( ctx, 0 );
        return 1;
    }

    r = CL_TP_GscNextRand();
    gsc_add_int( ctx, (int)( r % (unsigned int)maxVal ) );
    return 1;
}

static int CL_TP_GscFn_RandomFloat( gsc_Context *ctx )
{
    float maxVal;
    float scale;

    maxVal = gsc_get_float( ctx, 0 );
    if ( maxVal <= 0.0f ) {
        gsc_add_float( ctx, 0.0f );
        return 1;
    }

    scale = (float)CL_TP_GscNextRand() / (float)0xFFFFFFFFu;
    gsc_add_float( ctx, scale * maxVal );
    return 1;
}

static int CL_TP_GscFn_GetCvarInt( gsc_Context *ctx )
{
    const char *name = gsc_get_string( ctx, 0 );
    gsc_add_int( ctx, Cvar_VariableIntegerValue( name ? name : "" ) );
    return 1;
}

static int CL_TP_GscFn_GetCvarFloat( gsc_Context *ctx )
{
    const char *name = gsc_get_string( ctx, 0 );
    gsc_add_float( ctx, Cvar_VariableValue( name ? name : "" ) );
    return 1;
}

static int CL_TP_GscFn_GetCvar( gsc_Context *ctx )
{
    const char *name = gsc_get_string( ctx, 0 );
    gsc_add_string( ctx, Cvar_VariableString( name ? name : "" ) );
    return 1;
}

static int CL_TP_GscFn_Println( gsc_Context *ctx )
{
    int i;

    if ( !cl_thirdPersonDebug || !cl_thirdPersonDebug->integer ) {
        return 0;
    }

    Com_Printf( "thirdperson[gsc]:" );
    for ( i = 0; i < gsc_numargs( ctx ); ++i ) {
        Com_Printf( " %s", gsc_get_string( ctx, i ) );
    }
    Com_Printf( "\n" );
    return 0;
}

static int CL_TP_GscMeth_SetModel( gsc_Context *ctx )
{
    const char *modelRaw;

    if ( !s_tpGscEval || gsc_numargs( ctx ) < 1 || gsc_get_type( ctx, 0 ) == GSC_TYPE_UNDEFINED ) {
        return 0;
    }

    modelRaw = gsc_get_string( ctx, 0 );
    if ( modelRaw && modelRaw[0] ) {
        CL_TP_NormalizeModelPath( modelRaw, s_tpGscEval->baseModel, sizeof( s_tpGscEval->baseModel ) );
    }

    return 0;
}

static int CL_TP_GscMeth_SetViewModel( gsc_Context *ctx )
{
    const char *modelRaw;

    if ( !s_tpGscEval || gsc_numargs( ctx ) < 1 || gsc_get_type( ctx, 0 ) == GSC_TYPE_UNDEFINED ) {
        return 0;
    }

    modelRaw = gsc_get_string( ctx, 0 );
    if ( modelRaw && modelRaw[0] ) {
        CL_TP_NormalizeModelPath( modelRaw, s_tpGscEval->viewModel, sizeof( s_tpGscEval->viewModel ) );
    }

    return 0;
}

static int CL_TP_GscMeth_DetachAll( gsc_Context *ctx )
{
    (void)ctx;

    if ( !s_tpGscEval ) {
        return 0;
    }

    Com_Memset( s_tpGscEval->attachments, 0, sizeof( s_tpGscEval->attachments ) );
    s_tpGscEval->numAttachments = 0;
    return 0;
}

static int CL_TP_GscMeth_Attach( gsc_Context *ctx )
{
    const char *modelRaw;
    char modelPath[MAX_QPATH];
    char tagName[TP_TAGNAME_LEN];

    if ( !s_tpGscEval || gsc_numargs( ctx ) < 1 || gsc_get_type( ctx, 0 ) == GSC_TYPE_UNDEFINED ) {
        return 0;
    }

    modelRaw = gsc_get_string( ctx, 0 );
    if ( !modelRaw || !modelRaw[0] ) {
        return 0;
    }

    CL_TP_NormalizeModelPath( modelRaw, modelPath, sizeof( modelPath ) );
    tagName[0] = '\0';

    if ( gsc_numargs( ctx ) > 1 && gsc_get_type( ctx, 1 ) != GSC_TYPE_UNDEFINED ) {
        const char *tagRaw = gsc_get_string( ctx, 1 );
        if ( tagRaw ) {
            Q_strncpyz( tagName, tagRaw, sizeof( tagName ) );
        }
    }

    if ( !tagName[0] ) {
        const char *defaultTag = CL_TP_DefaultTagForAttachment( modelPath );
        if ( defaultTag[0] ) {
            Q_strncpyz( tagName, defaultTag, sizeof( tagName ) );
        } else {
            return 0;
        }
    }

    CL_TP_AddAttachment( s_tpGscEval->attachments, &s_tpGscEval->numAttachments, modelPath, tagName );
    return 0;
}

static int CL_TP_GscMeth_GetViewModel( gsc_Context *ctx )
{
    if ( !s_tpGscEval ) {
        gsc_add_string( ctx, "" );
        return 1;
    }

    gsc_add_string( ctx, s_tpGscEval->viewModel );
    return 1;
}

static int CL_TP_GscMeth_GetAttachSize( gsc_Context *ctx )
{
    if ( !s_tpGscEval ) {
        gsc_add_int( ctx, 0 );
        return 1;
    }

    gsc_add_int( ctx, s_tpGscEval->numAttachments );
    return 1;
}

static int CL_TP_GscMeth_GetAttachModelName( gsc_Context *ctx )
{
    int index;

    if ( !s_tpGscEval || gsc_numargs( ctx ) < 1 ) {
        gsc_add_string( ctx, "" );
        return 1;
    }

    index = (int)gsc_get_int( ctx, 0 );
    if ( index < 0 || index >= s_tpGscEval->numAttachments ) {
        gsc_add_string( ctx, "" );
        return 1;
    }

    gsc_add_string( ctx, s_tpGscEval->attachments[index].modelPath );
    return 1;
}

static int CL_TP_GscMeth_GetAttachTagName( gsc_Context *ctx )
{
    int index;

    if ( !s_tpGscEval || gsc_numargs( ctx ) < 1 ) {
        gsc_add_string( ctx, "" );
        return 1;
    }

    index = (int)gsc_get_int( ctx, 0 );
    if ( index < 0 || index >= s_tpGscEval->numAttachments ) {
        gsc_add_string( ctx, "" );
        return 1;
    }

    gsc_add_string( ctx, s_tpGscEval->attachments[index].tagName );
    return 1;
}

static int CL_TP_GscMeth_GetAttachIgnoreCollision( gsc_Context *ctx )
{
    (void)ctx;
    gsc_add_bool( ctx, qfalse );
    return 1;
}

static void CL_TP_GscRegisterFunctions( gsc_Context *ctx )
{
    gsc_register_function( ctx, NULL, "isdefined", CL_TP_GscFn_IsDefined );

    gsc_register_function( ctx, NULL, "randomint", CL_TP_GscFn_RandomInt );
    gsc_register_function( ctx, NULL, "randomInt", CL_TP_GscFn_RandomInt );

    gsc_register_function( ctx, NULL, "randomfloat", CL_TP_GscFn_RandomFloat );
    gsc_register_function( ctx, NULL, "randomFloat", CL_TP_GscFn_RandomFloat );

    gsc_register_function( ctx, NULL, "getcvarint", CL_TP_GscFn_GetCvarInt );
    gsc_register_function( ctx, NULL, "getCvarInt", CL_TP_GscFn_GetCvarInt );

    gsc_register_function( ctx, NULL, "getcvarfloat", CL_TP_GscFn_GetCvarFloat );
    gsc_register_function( ctx, NULL, "getCvarFloat", CL_TP_GscFn_GetCvarFloat );

    gsc_register_function( ctx, NULL, "getcvar", CL_TP_GscFn_GetCvar );
    gsc_register_function( ctx, NULL, "getCvar", CL_TP_GscFn_GetCvar );

    gsc_register_function( ctx, NULL, "println", CL_TP_GscFn_Println );
}

static void CL_TP_GscCreateSelfObject( gsc_Context *ctx )
{
    int proxyObj;
    int methodsObj;
    int selfObj;

    proxyObj = gsc_add_tagged_object( ctx, "#entity_proxy" );
    methodsObj = gsc_add_object( ctx );

    gsc_add_function( ctx, CL_TP_GscMeth_SetModel );
    gsc_object_set_field( ctx, methodsObj, "setModel" );

    gsc_add_function( ctx, CL_TP_GscMeth_SetViewModel );
    gsc_object_set_field( ctx, methodsObj, "setViewModel" );

    gsc_add_function( ctx, CL_TP_GscMeth_DetachAll );
    gsc_object_set_field( ctx, methodsObj, "detachAll" );

    gsc_add_function( ctx, CL_TP_GscMeth_Attach );
    gsc_object_set_field( ctx, methodsObj, "attach" );

    gsc_add_function( ctx, CL_TP_GscMeth_GetViewModel );
    gsc_object_set_field( ctx, methodsObj, "getViewModel" );

    gsc_add_function( ctx, CL_TP_GscMeth_GetAttachSize );
    gsc_object_set_field( ctx, methodsObj, "getAttachSize" );

    gsc_add_function( ctx, CL_TP_GscMeth_GetAttachModelName );
    gsc_object_set_field( ctx, methodsObj, "getAttachModelName" );

    gsc_add_function( ctx, CL_TP_GscMeth_GetAttachTagName );
    gsc_object_set_field( ctx, methodsObj, "getAttachTagName" );

    gsc_add_function( ctx, CL_TP_GscMeth_GetAttachIgnoreCollision );
    gsc_object_set_field( ctx, methodsObj, "getAttachIgnoreCollision" );

    gsc_object_set_field( ctx, proxyObj, "__call" );

    selfObj = gsc_add_tagged_object( ctx, "#entity" );
    gsc_object_set_proxy( ctx, selfObj, proxyObj );
    gsc_set_global( ctx, "self" );

    gsc_add_tagged_object( ctx, "#anim" );
    gsc_set_global( ctx, "anim" );

    gsc_add_tagged_object( ctx, "#level" );
    gsc_set_global( ctx, "level" );

    gsc_add_tagged_object( ctx, "#game" );
    gsc_set_global( ctx, "game" );

    gsc_pop( ctx, 1 ); /* proxyObj */
}

static qboolean CL_TP_ParseCharacterScriptGsc( const char *scriptPath,
                                               char *outBaseModel,
                                               tpAttachment_t *outAttachments,
                                               int *outNumAttachments )
{
    gsc_CreateOptions options;
    gsc_Context *ctx;
    tpGscEvalState_t evalState;
    char scriptNamespace[MAX_QPATH];
    const char *nextDep;
    int status;
    int i;
    qboolean ok;

    *outNumAttachments = 0;
    outBaseModel[0] = '\0';
    ok = qfalse;

    Com_Memset( &evalState, 0, sizeof( evalState ) );
    evalState.randState = (unsigned int)MSG_HashKey( scriptPath, 128 ) ^ (unsigned int)cl.serverTime ^ 0x9E3779B9u;
    if ( !evalState.randState ) {
        evalState.randState = 1;
    }

    s_tpGscEval = &evalState;

    Com_Memset( &options, 0, sizeof( options ) );
    options.allocate_memory = CL_TP_GscAllocMemory;
    options.free_memory = CL_TP_GscFreeMemory;
    options.read_file = CL_TP_GscReadFile;
    options.userdata = NULL;
    options.verbose = ( cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) ? 1 : 0;
    options.main_memory_size = 16 * 1024 * 1024;
    options.temp_memory_size = 2 * 1024 * 1024;
    options.string_table_memory_size = 1024 * 1024;
    options.default_self = "self";
    options.max_threads = 32;

    ctx = gsc_create( options );
    if ( !ctx ) {
        goto cleanup;
    }

    CL_TP_GscRegisterFunctions( ctx );
    CL_TP_GscCreateSelfObject( ctx );

    CL_TP_GscBuildNamespace( scriptPath, scriptNamespace, sizeof( scriptNamespace ) );

    status = gsc_compile( ctx, scriptNamespace, 0 );
    while ( status == GSC_OK && ( nextDep = gsc_next_compile_dependency( ctx ) ) != NULL ) {
        status = gsc_compile( ctx, nextDep, 0 );
    }

    if ( status != GSC_OK ) {
        if ( cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
            Com_Printf( "thirdperson[gsc]: compile failed for '%s' (%d)\n", scriptNamespace, status );
        }
        gsc_destroy( ctx );
        ctx = NULL;
        goto cleanup;
    }

    status = gsc_link( ctx );
    if ( status != GSC_OK ) {
        if ( cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
            Com_Printf( "thirdperson[gsc]: link failed for '%s' (%d)\n", scriptNamespace, status );
        }
        gsc_destroy( ctx );
        ctx = NULL;
        goto cleanup;
    }

    status = gsc_call( ctx, scriptNamespace, "main", 0 );
    if ( status != GSC_OK ) {
        if ( cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
            Com_Printf( "thirdperson[gsc]: call failed for '%s::main' (%d)\n", scriptNamespace, status );
        }
        gsc_destroy( ctx );
        ctx = NULL;
        goto cleanup;
    }

    while ( ( status = gsc_update( ctx, 0.05f ) ) == GSC_YIELD ) {
        /* run script threads until completion */
    }

    if ( status != GSC_OK ) {
        if ( cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
            Com_Printf( "thirdperson[gsc]: update failed for '%s' (%d)\n", scriptNamespace, status );
        }
        gsc_destroy( ctx );
        ctx = NULL;
        goto cleanup;
    }

    Q_strncpyz( outBaseModel, evalState.baseModel, MAX_QPATH );
    *outNumAttachments = evalState.numAttachments;
    for ( i = 0; i < evalState.numAttachments; ++i ) {
        outAttachments[i] = evalState.attachments[i];
    }

    ok = ( outBaseModel[0] != '\0' ) ? qtrue : qfalse;

    gsc_destroy( ctx );
    ctx = NULL;

cleanup:
    CL_TP_GscFreeTrackedSources( &evalState );
    s_tpGscEval = NULL;
    return ok;
}

static qboolean CL_TP_ParseCharacterScript( const char *scriptPath,
                                            char *outBaseModel,
                                            tpAttachment_t *outAttachments,
                                            int *outNumAttachments )
{
    char *fileText;
    long fileLen;
    const char *scan;
    char hatModel[MAX_QPATH];
    qboolean foundBaseModel;

    *outNumAttachments = 0;
    outBaseModel[0] = '\0';
    hatModel[0] = '\0';
    foundBaseModel = qfalse;

    fileText = NULL;
    fileLen = FS_ReadFile( scriptPath, (void **)&fileText );
    if ( fileLen <= 0 || !fileText ) {
        return qfalse;
    }

    scan = fileText;
    while ( ( scan = Q_stristr( scan, "setModel(" ) ) != NULL ) {
        char modelRaw[MAX_QPATH];
        char modelPath[MAX_QPATH];

        if ( CL_TP_ParseQuoted( scan, NULL, modelRaw, sizeof( modelRaw ) ) ) {
            CL_TP_NormalizeModelPath( modelRaw, modelPath, sizeof( modelPath ) );
            Q_strncpyz( outBaseModel, modelPath, MAX_QPATH );
            foundBaseModel = qtrue;
            break;
        }

        scan += 9;
    }

    if ( !foundBaseModel ) {
        scan = fileText;
        while ( ( scan = Q_stristr( scan, "setModelFromArray(" ) ) != NULL ) {
            const char *open;
            const char *close;
            char args[512];
            int argsLen;
            char modelPath[MAX_QPATH];

            open = strchr( scan, '(' );
            close = open ? strchr( open, ')' ) : NULL;
            if ( !open || !close || close <= open + 1 ) {
                scan += 17;
                continue;
            }

            argsLen = (int)( close - ( open + 1 ) );
            if ( argsLen >= (int)sizeof( args ) ) {
                argsLen = sizeof( args ) - 1;
            }

            memcpy( args, open + 1, argsLen );
            args[argsLen] = '\0';

            if ( CL_TP_ResolveAliasToModel( args, modelPath, sizeof( modelPath ) ) ) {
                Q_strncpyz( outBaseModel, modelPath, MAX_QPATH );
                foundBaseModel = qtrue;
                break;
            }

            scan = close + 1;
        }
    }

    scan = fileText;
    while ( ( scan = Q_stristr( scan, "self.hatModel" ) ) != NULL ) {
        const char *eq;
        const char *semi;
        char modelRaw[MAX_QPATH];
        char modelPath[MAX_QPATH];
        char expr[512];
        int exprLen;

        eq = strchr( scan, '=' );
        semi = strchr( scan, ';' );
        if ( !eq || ( semi && eq > semi ) ) {
            scan += 13;
            continue;
        }

        if ( CL_TP_ParseQuoted( eq + 1, NULL, modelRaw, sizeof( modelRaw ) ) ) {
            CL_TP_NormalizeModelPath( modelRaw, modelPath, sizeof( modelPath ) );
            Q_strncpyz( hatModel, modelPath, sizeof( hatModel ) );
            break;
        }

        exprLen = semi ? (int)( semi - ( eq + 1 ) ) : (int)strlen( eq + 1 );
        if ( exprLen >= (int)sizeof( expr ) ) {
            exprLen = sizeof( expr ) - 1;
        }
        if ( exprLen > 0 ) {
            memcpy( expr, eq + 1, exprLen );
        }
        expr[exprLen] = '\0';
        if ( CL_TP_ResolveAliasToModel( expr, modelPath, sizeof( modelPath ) ) ) {
            Q_strncpyz( hatModel, modelPath, sizeof( hatModel ) );
            break;
        }

        scan += 13;
    }

    scan = fileText;
    while ( ( scan = Q_stristr( scan, "attachFromArray(" ) ) != NULL &&
            *outNumAttachments < TP_MAX_ATTACHMENTS ) {
        const char *open;
        const char *close;
        char args[512];
        int argsLen;
        char attachModelPath[MAX_QPATH];
        const char *defaultTag;

        open = strchr( scan, '(' );
        close = open ? strchr( open, ')' ) : NULL;
        if ( !open || !close || close <= open + 1 ) {
            scan += 16;
            continue;
        }

        argsLen = (int)( close - ( open + 1 ) );
        if ( argsLen >= (int)sizeof( args ) ) {
            argsLen = sizeof( args ) - 1;
        }

        memcpy( args, open + 1, argsLen );
        args[argsLen] = '\0';

        if ( CL_TP_ResolveAliasToModel( args, attachModelPath, sizeof( attachModelPath ) ) ) {
            defaultTag = CL_TP_DefaultTagForAttachment( attachModelPath );
            if ( defaultTag[0] ) {
                CL_TP_AddAttachment( outAttachments, outNumAttachments,
                                     attachModelPath, defaultTag );
            }
        }

        scan = close + 1;
    }

    scan = fileText;
    while ( ( scan = Q_stristr( scan, "attach(" ) ) != NULL &&
            *outNumAttachments < TP_MAX_ATTACHMENTS ) {
        const char *open;
        const char *close;
        char args[512];
        int argsLen;
        char attachModelRaw[MAX_QPATH];
        char attachModelPath[MAX_QPATH];
        char attachTag[TP_TAGNAME_LEN];
        const char *afterFirst;

        open = strchr( scan, '(' );
        close = open ? strchr( open, ')' ) : NULL;
        if ( !open || !close || close <= open + 1 ) {
            scan += 7;
            continue;
        }

        argsLen = (int)( close - ( open + 1 ) );
        if ( argsLen >= (int)sizeof( args ) ) {
            argsLen = sizeof( args ) - 1;
        }

        memcpy( args, open + 1, argsLen );
        args[argsLen] = '\0';

        attachModelPath[0] = '\0';
        attachTag[0] = '\0';

        if ( Q_stristr( args, "self.hatModel" ) && hatModel[0] ) {
            Q_strncpyz( attachModelPath, hatModel, sizeof( attachModelPath ) );
        } else if ( CL_TP_ParseQuoted( args, &afterFirst, attachModelRaw,
                                        sizeof( attachModelRaw ) ) ) {
            CL_TP_NormalizeModelPath( attachModelRaw, attachModelPath,
                                      sizeof( attachModelPath ) );

            if ( CL_TP_ParseQuoted( afterFirst, NULL, attachTag,
                                    sizeof( attachTag ) ) ) {
                /* Keep explicit tag if present, including TAG_* bones. */
            }
        }

        if ( attachModelPath[0] && !attachTag[0] ) {
            const char *defaultTag = CL_TP_DefaultTagForAttachment( attachModelPath );
            if ( defaultTag[0] ) {
                Q_strncpyz( attachTag, defaultTag, sizeof( attachTag ) );
            } else {
                /* Many empty-tag gear models expect full bone-merge.
                 * Skip those for now to avoid floating gear. */
                scan = close + 1;
                continue;
            }
        }

        CL_TP_AddAttachment( outAttachments, outNumAttachments,
                             attachModelPath, attachTag );
        scan = close + 1;
    }

    FS_FreeFile( fileText );
    return foundBaseModel;
}

static void CL_TP_LoadAnimations( void )
{
    int i;

    for ( i = 0; i < TP_LEG_ANIM_COUNT; ++i ) {
        s_tpChar.legAnims[i] = 0;
        if ( re.RegisterXAnim ) {
            s_tpChar.legAnims[i] = re.RegisterXAnim( s_tpLegAnimNames[i] );
        }

        if ( !s_tpChar.legAnims[i] && cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
            Com_Printf( "thirdperson: missing legs xanim '%s'\n", s_tpLegAnimNames[i] );
        }
    }

    for ( i = 0; i < TP_TORSO_ANIM_COUNT; ++i ) {
        int c;
        s_tpChar.torsoAnims[i] = 0;
        for ( c = 0; c < (int)ARRAY_LEN( s_tpTorsoAnimCandidates[i] ); ++c ) {
            const char *name = s_tpTorsoAnimCandidates[i][c];
            if ( !name || !name[0] ) {
                continue;
            }
            if ( !re.RegisterXAnim ) {
                break;
            }

            s_tpChar.torsoAnims[i] = re.RegisterXAnim( name );
            if ( s_tpChar.torsoAnims[i] ) {
                break;
            }
        }

        if ( !s_tpChar.torsoAnims[i] && cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
            Com_Printf( "thirdperson: missing torso xanim set for slot %d\n", i );
        }
    }

    s_tpChar.currentLegAnim = TP_LEG_ANIM_STAND_IDLE;
    s_tpChar.currentTorsoAnim = TP_TORSO_ANIM_STAND_IDLE;
    s_tpChar.legAnimStartTime = cl.serverTime;
    s_tpChar.torsoAnimStartTime = cl.serverTime;
}

static qboolean CL_TP_AttachmentListsEqual( const tpAttachment_t *a, int aCount,
                                            const tpAttachment_t *b, int bCount )
{
    int i;

    if ( aCount != bCount ) {
        return qfalse;
    }

    for ( i = 0; i < aCount; ++i ) {
        if ( Q_stricmp( a[i].modelPath, b[i].modelPath ) ||
             Q_stricmp( a[i].tagName, b[i].tagName ) ) {
            return qfalse;
        }
    }

    return qtrue;
}

static void CL_TP_LoadCharacterAssets( void )
{
    char desiredModelPath[MAX_QPATH];
    char desiredScriptPath[MAX_QPATH];
    tpAttachment_t desiredAttachments[TP_MAX_ATTACHMENTS];
    int desiredAttachmentCount;
    qboolean fromScript;
    int i;

    desiredModelPath[0] = '\0';
    desiredScriptPath[0] = '\0';
    desiredAttachmentCount = 0;
    fromScript = qfalse;

    if ( cl_thirdPersonModel && cl_thirdPersonModel->string[0] ) {
        CL_TP_NormalizeModelPath( cl_thirdPersonModel->string,
                                  desiredModelPath, sizeof( desiredModelPath ) );
    } else {
        CL_TP_BuildCharacterScriptPath( cl_thirdPersonCharacter ? cl_thirdPersonCharacter->string : "",
                                        desiredScriptPath, sizeof( desiredScriptPath ) );

        if ( cl_thirdPersonUseGsc && cl_thirdPersonUseGsc->integer ) {
            fromScript = CL_TP_ParseCharacterScriptGsc( desiredScriptPath,
                                                        desiredModelPath,
                                                        desiredAttachments,
                                                        &desiredAttachmentCount );
            if ( !fromScript && cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
                Com_Printf( "thirdperson[gsc]: fallback to parser for '%s'\n", desiredScriptPath );
            }
        }

        if ( !fromScript ) {
            fromScript = CL_TP_ParseCharacterScript( desiredScriptPath,
                                                     desiredModelPath,
                                                     desiredAttachments,
                                                     &desiredAttachmentCount );
        }
    }

    if ( !desiredModelPath[0] ) {
        CL_TP_NormalizeModelPath( "axis_default", desiredModelPath,
                                  sizeof( desiredModelPath ) );
    }

    if ( s_tpChar.baseModel &&
         !Q_stricmp( s_tpChar.loadedModelPath, desiredModelPath ) &&
         !Q_stricmp( s_tpChar.loadedScriptPath, desiredScriptPath ) &&
         !Q_stricmp( s_tpChar.loadedModelOverride,
                    cl_thirdPersonModel ? cl_thirdPersonModel->string : "" ) &&
         CL_TP_AttachmentListsEqual( s_tpChar.attachments, s_tpChar.numAttachments,
                                     desiredAttachments, desiredAttachmentCount ) ) {
        return;
    }

    Com_Memset( &s_tpChar.attachments, 0, sizeof( s_tpChar.attachments ) );
    s_tpChar.numAttachments = 0;

    s_tpChar.baseModel = CL_TP_RegisterModelWithFallback( desiredModelPath,
                                                          desiredModelPath,
                                                          sizeof( desiredModelPath ) );

    if ( !s_tpChar.baseModel ) {
        Com_Printf( "thirdperson: failed to load model '%s' (and fallback playerbody models)\n",
                    desiredModelPath );
    }

    for ( i = 0; i < desiredAttachmentCount; ++i ) {
        s_tpChar.attachments[s_tpChar.numAttachments] = desiredAttachments[i];
        s_tpChar.attachments[s_tpChar.numAttachments].hModel =
            re.RegisterModel( s_tpChar.attachments[s_tpChar.numAttachments].modelPath );

        if ( !s_tpChar.attachments[s_tpChar.numAttachments].hModel &&
             cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
            Com_Printf( "thirdperson: missing attachment '%s'\n",
                        s_tpChar.attachments[s_tpChar.numAttachments].modelPath );
        }

        s_tpChar.numAttachments++;
    }

    Q_strncpyz( s_tpChar.loadedModelPath, desiredModelPath, sizeof( s_tpChar.loadedModelPath ) );
    Q_strncpyz( s_tpChar.loadedScriptPath, desiredScriptPath, sizeof( s_tpChar.loadedScriptPath ) );
    Q_strncpyz( s_tpChar.loadedModelOverride,
                cl_thirdPersonModel ? cl_thirdPersonModel->string : "",
                sizeof( s_tpChar.loadedModelOverride ) );

    if ( cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
        if ( fromScript ) {
            Com_Printf( "thirdperson: script '%s' -> model '%s' (%d attachments)\n",
                        desiredScriptPath, desiredModelPath, s_tpChar.numAttachments );
        } else {
            Com_Printf( "thirdperson: override model '%s' (%d attachments)\n",
                        desiredModelPath, s_tpChar.numAttachments );
        }
    }
}

static float CL_TP_GetSnapshotLerpFrac( const clSnapshot_t **outPrevSnap )
{
    const clSnapshot_t *prevSnap;
    int prevMsgNum;
    int denom;
    float frac;

    *outPrevSnap = NULL;

    prevMsgNum = cl.snap.messageNum - 1;
    if ( prevMsgNum < 0 ) {
        return 1.0f;
    }

    prevSnap = &cl.snapshots[prevMsgNum & PACKET_MASK];
    if ( !prevSnap->valid || prevSnap->messageNum != prevMsgNum ) {
        return 1.0f;
    }

    denom = cl.snap.serverTime - prevSnap->serverTime;
    if ( denom <= 0 ) {
        return 1.0f;
    }

    frac = (float)( cl.serverTime - prevSnap->serverTime ) / (float)denom;
    if ( frac < 0.0f ) {
        frac = 0.0f;
    } else if ( frac > 1.0f ) {
        frac = 1.0f;
    }

    *outPrevSnap = prevSnap;
    return frac;
}

static void CL_TP_GetInterpolatedState( vec3_t outOrigin, vec3_t outVelocity, int *outViewHeight )
{
    const clSnapshot_t *prevSnap;
    float frac;
    int i;

    frac = CL_TP_GetSnapshotLerpFrac( &prevSnap );
    if ( !prevSnap ) {
        VectorCopy( cl.snap.ps.origin, outOrigin );
        VectorCopy( cl.snap.ps.velocity, outVelocity );
        *outViewHeight = cl.snap.ps.viewheight;
        return;
    }

    for ( i = 0; i < 3; ++i ) {
        outOrigin[i] = prevSnap->ps.origin[i] +
                       frac * ( cl.snap.ps.origin[i] - prevSnap->ps.origin[i] );
        outVelocity[i] = prevSnap->ps.velocity[i] +
                         frac * ( cl.snap.ps.velocity[i] - prevSnap->ps.velocity[i] );
    }

    *outViewHeight = (int)( prevSnap->ps.viewheight +
                            frac * (float)( cl.snap.ps.viewheight - prevSnap->ps.viewheight ) );
}

static float CL_TP_StepYawToward( float currentYaw, float desiredYaw, float maxStep )
{
    float delta;

    delta = AngleSubtract( desiredYaw, currentYaw );
    if ( delta > maxStep ) {
        delta = maxStep;
    } else if ( delta < -maxStep ) {
        delta = -maxStep;
    }

    return AngleNormalize360( currentYaw + delta );
}

static void CL_TP_DeriveStanceFlags( const playerState_t *ps,
                                     qboolean *outCrouched, qboolean *outProne )
{
    int legsAnim;

    *outCrouched = ( ps->pm_flags & PMF_DUCKED ) ? qtrue : qfalse;
    *outProne = ( ps->viewheight <= ( PRONE_VIEWHEIGHT + 1 ) );

    legsAnim = ps->legsAnim & ~ANIM_TOGGLEBIT;
    switch ( legsAnim ) {
        case LEGS_WALKCR:
        case LEGS_IDLECR:
        case LEGS_BACKCR:
            *outCrouched = qtrue;
            break;
        default:
            break;
    }
}

static tpLegAnimSlot_t CL_TP_LegIdleAnimForStance( qboolean crouched, qboolean prone )
{
    if ( prone ) {
        return TP_LEG_ANIM_PRONE_IDLE;
    }
    if ( crouched ) {
        return TP_LEG_ANIM_CROUCH_IDLE;
    }
    return TP_LEG_ANIM_STAND_IDLE;
}

static tpTorsoAnimSlot_t CL_TP_TorsoIdleAnimForStance( qboolean crouched, qboolean prone )
{
    if ( prone ) {
        return TP_TORSO_ANIM_PRONE_IDLE;
    }
    if ( crouched ) {
        return TP_TORSO_ANIM_CROUCH_IDLE;
    }
    return TP_TORSO_ANIM_STAND_IDLE;
}

static tpTorsoAnimSlot_t CL_TP_TorsoFireAnimForStance( qboolean crouched, qboolean prone )
{
    if ( prone ) {
        return TP_TORSO_ANIM_PRONE_FIRE;
    }
    if ( crouched ) {
        return TP_TORSO_ANIM_CROUCH_FIRE;
    }
    return TP_TORSO_ANIM_STAND_FIRE;
}

static tpLegAnimSlot_t CL_TP_MoveAnimForDir( int dir, qboolean crouched, qboolean prone, qboolean forceBack )
{
    if ( forceBack ) {
        dir = 4;
    }

    if ( prone ) {
        switch ( dir ) {
            case 4:
            case 3:
            case 5:
                return TP_LEG_ANIM_PRONE_BACK;
            case 2:
                return TP_LEG_ANIM_PRONE_LEFT;
            case 6:
                return TP_LEG_ANIM_PRONE_RIGHT;
            default:
                return TP_LEG_ANIM_PRONE_FWD;
        }
    }

    if ( crouched ) {
        switch ( dir ) {
            case 4:
            case 3:
            case 5:
                return TP_LEG_ANIM_CROUCH_BACK;
            case 2:
                return TP_LEG_ANIM_CROUCH_LEFT;
            case 6:
                return TP_LEG_ANIM_CROUCH_RIGHT;
            default:
                return TP_LEG_ANIM_CROUCH_FWD;
        }
    }

    switch ( dir ) {
        case 4:
        case 3:
        case 5:
            return TP_LEG_ANIM_STAND_BACK;
        case 2:
            return TP_LEG_ANIM_STAND_LEFT;
        case 6:
            return TP_LEG_ANIM_STAND_RIGHT;
        default:
            return TP_LEG_ANIM_STAND_FWD;
    }
}

static tpLegAnimSlot_t CL_TP_ChooseLegAnimForPlayerState( const playerState_t *ps )
{
    int legsAnim;
    float xyspeed;
    qboolean moving;
    qboolean crouched;
    qboolean prone;
    qboolean forceBack;
    int dir;

    legsAnim = ps->legsAnim & ~ANIM_TOGGLEBIT;

    xyspeed = sqrtf( ps->velocity[0] * ps->velocity[0] +
                     ps->velocity[1] * ps->velocity[1] );
    moving = qfalse;
    CL_TP_DeriveStanceFlags( ps, &crouched, &prone );
    forceBack = qfalse;
    dir = ps->movementDir & 7;

    if ( ps->pm_type != PM_NORMAL && ps->pm_type != PM_DEAD ) {
        return CL_TP_LegIdleAnimForStance( crouched, prone );
    }

    switch ( legsAnim ) {
        case LEGS_WALKCR:
            crouched = qtrue;
            moving = qtrue;
            break;
        case LEGS_IDLECR:
            crouched = qtrue;
            moving = qfalse;
            break;
        case LEGS_BACKCR:
            crouched = qtrue;
            moving = qtrue;
            forceBack = qtrue;
            break;
        case LEGS_WALK:
        case LEGS_RUN:
        case LEGS_SWIM:
        case LEGS_JUMP:
        case LEGS_LAND:
        case LEGS_JUMPB:
        case LEGS_LANDB:
            moving = qtrue;
            break;
        case LEGS_BACK:
        case LEGS_BACKWALK:
            moving = qtrue;
            forceBack = qtrue;
            break;
        default:
            moving = qfalse;
            break;
    }

    if ( !moving ) {
        moving = ( xyspeed > ( cl_thirdPersonMoveThreshold ? cl_thirdPersonMoveThreshold->value : 20.0f ) );
    }

    if ( !moving || ps->groundEntityNum == ENTITYNUM_NONE ) {
        return CL_TP_LegIdleAnimForStance( crouched, prone );
    }

    return CL_TP_MoveAnimForDir( dir, crouched, prone, forceBack );
}

static tpTorsoAnimSlot_t CL_TP_ChooseTorsoAnimForPlayerState( const playerState_t *ps )
{
    int torsoAnim;
    qboolean crouched;
    qboolean prone;
    qboolean firing;

    torsoAnim = ps->torsoAnim & ~ANIM_TOGGLEBIT;
    CL_TP_DeriveStanceFlags( ps, &crouched, &prone );

    firing = ( torsoAnim == TORSO_ATTACK || torsoAnim == TORSO_ATTACK2 ) ? qtrue : qfalse;
    if ( ps->pm_type != PM_NORMAL && ps->pm_type != PM_DEAD ) {
        firing = qfalse;
    }

    if ( firing ) {
        return CL_TP_TorsoFireAnimForStance( crouched, prone );
    }

    return CL_TP_TorsoIdleAnimForStance( crouched, prone );
}

static qhandle_t CL_TP_GetLegAnimHandleForState( tpLegAnimSlot_t slot )
{
    if ( slot < 0 || slot >= TP_LEG_ANIM_COUNT ) {
        slot = TP_LEG_ANIM_STAND_IDLE;
    }

    if ( s_tpChar.legAnims[slot] ) {
        return s_tpChar.legAnims[slot];
    }

    return s_tpChar.legAnims[TP_LEG_ANIM_STAND_IDLE];
}

static qhandle_t CL_TP_GetTorsoAnimHandleForState( tpTorsoAnimSlot_t slot )
{
    if ( slot < 0 || slot >= TP_TORSO_ANIM_COUNT ) {
        slot = TP_TORSO_ANIM_STAND_IDLE;
    }

    if ( s_tpChar.torsoAnims[slot] ) {
        return s_tpChar.torsoAnims[slot];
    }

    if ( s_tpChar.torsoAnims[TP_TORSO_ANIM_STAND_IDLE] ) {
        return s_tpChar.torsoAnims[TP_TORSO_ANIM_STAND_IDLE];
    }

    return 0;
}

static float CL_TP_ComputeAnimFrame( qhandle_t animHandle, int animStartTime )
{
    int fps;
    int numFrames;
    float elapsed;
    float frame;
    float rate;

    if ( !animHandle ) {
        return 0.0f;
    }

    fps = re.XAnimFramerate ? re.XAnimFramerate( animHandle ) : 30;
    numFrames = re.XAnimNumFrames ? re.XAnimNumFrames( animHandle ) : 1;

    if ( fps <= 0 ) {
        fps = 30;
    }
    if ( numFrames <= 0 ) {
        numFrames = 1;
    }

    rate = cl_thirdPersonAnimRate ? cl_thirdPersonAnimRate->value : 1.0f;
    if ( rate <= 0.0f ) {
        rate = 1.0f;
    }

    elapsed = (float)( cl.serverTime - animStartTime ) * 0.001f;
    frame = elapsed * (float)fps * rate;

    if ( numFrames > 1 ) {
        frame = fmodf( frame, (float)numFrames );
    } else {
        frame = 0.0f;
    }

    return frame;
}

static qboolean CL_TP_PositionOnTag( refEntity_t *ent, const refEntity_t *parent,
                                     const char *tagName )
{
    orientation_t tag;
    vec3_t origin;
    vec3_t parentAxis[3];

    if ( !tagName || !tagName[0] ) {
        return qfalse;
    }

    if ( !re.LerpTag( &tag, parent->hModel, 0, 0, 1.0f, tagName ) ) {
        return qfalse;
    }

    VectorCopy( parent->origin, origin );
    VectorMA( origin, tag.origin[0], parent->axis[0], origin );
    VectorMA( origin, tag.origin[1], parent->axis[1], origin );
    VectorMA( origin, tag.origin[2], parent->axis[2], origin );

    VectorCopy( origin, ent->origin );
    VectorCopy( origin, ent->oldorigin );

    VectorCopy( parent->axis[0], parentAxis[0] );
    VectorCopy( parent->axis[1], parentAxis[1] );
    VectorCopy( parent->axis[2], parentAxis[2] );
    MatrixMultiply( tag.axis, parentAxis, ent->axis );

    return qtrue;
}

static qboolean CL_TP_PositionAttachment( refEntity_t *ent, const refEntity_t *parent,
                                          const tpAttachment_t *attachment )
{
    static const char *headFallbackTags[] = {
        "bip01 spine2", "bip01 neck", "neck", "tag_head", "j_head", "bip01 head", "head", "tag_helmet"
    };
    static const char *helmetFallbackTags[] = {
        "tag_helmet", "tag_head", "j_head", "bip01 head", "head"
    };
    int i;

    if ( attachment->tagName[0] &&
         CL_TP_PositionOnTag( ent, parent, attachment->tagName ) ) {
        return qtrue;
    }

    if ( CL_TP_IsHeadLikeModel( attachment->modelPath ) ) {
        for ( i = 0; i < (int)ARRAY_LEN( headFallbackTags ); ++i ) {
            if ( CL_TP_PositionOnTag( ent, parent, headFallbackTags[i] ) ) {
                return qtrue;
            }
        }
    } else if ( CL_TP_IsHelmetLikeModel( attachment->modelPath ) ) {
        for ( i = 0; i < (int)ARRAY_LEN( helmetFallbackTags ); ++i ) {
            if ( CL_TP_PositionOnTag( ent, parent, helmetFallbackTags[i] ) ) {
                return qtrue;
            }
        }
    }

    return qfalse;
}

static int CL_TP_FindMergedAttachmentIndex( void )
{
    int i;

    for ( i = 0; i < s_tpChar.numAttachments; ++i ) {
        if ( !s_tpChar.attachments[i].hModel ) {
            continue;
        }
        if ( CL_TP_IsHeadLikeModel( s_tpChar.attachments[i].modelPath ) ) {
            return i;
        }
    }

    return -1;
}

static void CL_TP_AddAttachments( const refEntity_t *baseEnt,
                                  const refEntity_t *mergedHeadEnt,
                                  int mergedAttachmentIndex )
{
    int i;

    for ( i = 0; i < s_tpChar.numAttachments; ++i ) {
        refEntity_t att;
        qboolean positioned;

        if ( i == mergedAttachmentIndex ) {
            continue;
        }
        if ( !s_tpChar.attachments[i].hModel ) {
            continue;
        }

        Com_Memset( &att, 0, sizeof( att ) );
        att.reType = RT_MODEL;
        att.hModel = s_tpChar.attachments[i].hModel;
        att.renderfx = baseEnt->renderfx;

        VectorCopy( baseEnt->origin, att.origin );
        VectorCopy( baseEnt->origin, att.oldorigin );
        VectorCopy( baseEnt->lightingOrigin, att.lightingOrigin );
        VectorCopy( baseEnt->axis[0], att.axis[0] );
        VectorCopy( baseEnt->axis[1], att.axis[1] );
        VectorCopy( baseEnt->axis[2], att.axis[2] );

        positioned = CL_TP_PositionAttachment( &att, baseEnt, &s_tpChar.attachments[i] );
        if ( !positioned && mergedHeadEnt &&
             ( CL_TP_IsHeadLikeModel( s_tpChar.attachments[i].modelPath ) ||
               CL_TP_IsHelmetLikeModel( s_tpChar.attachments[i].modelPath ) ) ) {
            CL_TP_PositionAttachment( &att, mergedHeadEnt, &s_tpChar.attachments[i] );
        }

        re.AddRefEntityToScene( &att );
    }
}

static void CL_TP_EnsureAssets( void )
{
    if ( !s_tpChar.legAnims[TP_LEG_ANIM_STAND_IDLE] ) {
        CL_TP_LoadAnimations();
    }

    if ( !s_tpChar.baseModel ||
         ( cl_thirdPersonModel && cl_thirdPersonModel->modified ) ||
         ( cl_thirdPersonCharacter && cl_thirdPersonCharacter->modified ) ||
         ( cl_thirdPersonUseGsc && cl_thirdPersonUseGsc->modified ) ) {
        CL_TP_LoadCharacterAssets();

        if ( cl_thirdPersonModel ) {
            cl_thirdPersonModel->modified = qfalse;
        }
        if ( cl_thirdPersonCharacter ) {
            cl_thirdPersonCharacter->modified = qfalse;
        }
        if ( cl_thirdPersonUseGsc ) {
            cl_thirdPersonUseGsc->modified = qfalse;
        }
    }
}

void CL_AddThirdPersonCharacter( const refdef_t *fd )
{
    refEntity_t ent;
    vec3_t angles;
    vec3_t interpOrigin;
    vec3_t interpVelocity;
    int interpViewHeight;
    float xyspeed;
    float desiredYaw;
    float maxYawStep;
    playerState_t interpPs;
    tpLegAnimSlot_t desiredLegAnim;
    tpTorsoAnimSlot_t desiredTorsoAnim;
    int mergedAttachmentIndex;
    refEntity_t mergedHeadEnt;
    qboolean hasMergedHeadEnt;
    qhandle_t legsAnimHandle;
    qhandle_t torsoAnimHandle;
    float legsAnimFrame;
    float torsoAnimFrame;
    qboolean useTorsoBlend;
    const char *torsoRootBone;

    if ( !fd || ( fd->rdflags & RDF_NOWORLDMODEL ) ) {
        return;
    }

    if ( !cl_drawThirdPersonCharacter || !cl_drawThirdPersonCharacter->integer ) {
        return;
    }

    if ( !cl.snap.valid ) {
        return;
    }

    if ( cl.snap.ps.pm_flags & PMF_FOLLOW ) {
        return;
    }

    if ( !Cvar_VariableIntegerValue( "cg_thirdPerson" ) ) {
        return;
    }

    CL_TP_EnsureAssets();

    if ( !s_tpChar.baseModel ) {
        return;
    }

    CL_TP_GetInterpolatedState( interpOrigin, interpVelocity, &interpViewHeight );
    interpPs = cl.snap.ps;
    VectorCopy( interpVelocity, interpPs.velocity );
    interpPs.viewheight = interpViewHeight;

    desiredLegAnim = CL_TP_ChooseLegAnimForPlayerState( &interpPs );
    desiredTorsoAnim = CL_TP_ChooseTorsoAnimForPlayerState( &interpPs );

    if ( desiredLegAnim != s_tpChar.currentLegAnim ) {
        s_tpChar.currentLegAnim = desiredLegAnim;
        s_tpChar.legAnimStartTime = cl.serverTime;
    }
    if ( desiredTorsoAnim != s_tpChar.currentTorsoAnim ) {
        s_tpChar.currentTorsoAnim = desiredTorsoAnim;
        s_tpChar.torsoAnimStartTime = cl.serverTime;
    }

    legsAnimHandle = CL_TP_GetLegAnimHandleForState( s_tpChar.currentLegAnim );
    torsoAnimHandle = CL_TP_GetTorsoAnimHandleForState( s_tpChar.currentTorsoAnim );
    legsAnimFrame = CL_TP_ComputeAnimFrame( legsAnimHandle, s_tpChar.legAnimStartTime );
    torsoAnimFrame = CL_TP_ComputeAnimFrame( torsoAnimHandle, s_tpChar.torsoAnimStartTime );
    useTorsoBlend = ( cl_thirdPersonBlendTorso && cl_thirdPersonBlendTorso->integer &&
                      torsoAnimHandle ) ? qtrue : qfalse;
    torsoRootBone = ( cl_thirdPersonTorsoRoot && cl_thirdPersonTorsoRoot->string[0] ) ?
                    cl_thirdPersonTorsoRoot->string : "bip01 spine2";

    Com_Memset( &ent, 0, sizeof( ent ) );
    ent.reType = RT_MODEL;
    ent.hModel = s_tpChar.baseModel;
    ent.renderfx = RF_LIGHTING_ORIGIN;

    VectorCopy( interpOrigin, ent.origin );
    ent.origin[2] += cl_thirdPersonZOffset ? cl_thirdPersonZOffset->value : 0.0f;

    VectorCopy( ent.origin, ent.oldorigin );
    VectorCopy( ent.origin, ent.lightingOrigin );

    xyspeed = sqrtf( interpVelocity[0] * interpVelocity[0] +
                     interpVelocity[1] * interpVelocity[1] );
    if ( cl_thirdPersonFaceMove && cl_thirdPersonFaceMove->integer &&
         xyspeed > ( cl_thirdPersonMoveThreshold ? cl_thirdPersonMoveThreshold->value : 20.0f ) &&
         interpPs.groundEntityNum != ENTITYNUM_NONE ) {
        desiredYaw = RAD2DEG( atan2f( interpVelocity[1], interpVelocity[0] ) );
    } else if ( cl_thirdPersonFaceView && cl_thirdPersonFaceView->integer ) {
        desiredYaw = cl.viewangles[YAW];
    } else if ( s_tpChar.renderYawValid ) {
        desiredYaw = s_tpChar.renderYaw;
    } else {
        desiredYaw = cl.viewangles[YAW];
    }

    if ( !s_tpChar.renderYawValid ) {
        s_tpChar.renderYaw = desiredYaw;
        s_tpChar.renderYawValid = qtrue;
    } else {
        maxYawStep = ( cl_thirdPersonYawLerpSpeed ? cl_thirdPersonYawLerpSpeed->value : 540.0f ) *
                     ( (float)cls.frametime * 0.001f );
        if ( maxYawStep < 0.0f ) {
            maxYawStep = 0.0f;
        }
        s_tpChar.renderYaw = CL_TP_StepYawToward( s_tpChar.renderYaw, desiredYaw, maxYawStep );
    }

    VectorClear( angles );
    angles[PITCH] = cl.viewangles[PITCH] * ( cl_thirdPersonPitchScale ? cl_thirdPersonPitchScale->value : 0.0f );
    angles[YAW] = s_tpChar.renderYaw + ( cl_thirdPersonYawOffset ? cl_thirdPersonYawOffset->value : 0.0f );
    AnglesToAxis( angles, ent.axis );

    mergedAttachmentIndex = CL_TP_FindMergedAttachmentIndex();
    hasMergedHeadEnt = qfalse;
    if ( mergedAttachmentIndex >= 0 &&
         s_tpChar.attachments[mergedAttachmentIndex].hModel ) {
        if ( useTorsoBlend && re.UpdateDObjPoseBlend && legsAnimHandle ) {
            re.UpdateDObjPoseBlend( s_tpChar.baseModel,
                                    s_tpChar.attachments[mergedAttachmentIndex].hModel,
                                    legsAnimHandle, legsAnimFrame,
                                    torsoAnimHandle, torsoAnimFrame,
                                    torsoRootBone );
        } else if ( re.UpdateDObjPose && ( legsAnimHandle || torsoAnimHandle ) ) {
            qhandle_t singleAnim = legsAnimHandle ? legsAnimHandle : torsoAnimHandle;
            float singleFrame = legsAnimHandle ? legsAnimFrame : torsoAnimFrame;
            re.UpdateDObjPose( s_tpChar.baseModel,
                               s_tpChar.attachments[mergedAttachmentIndex].hModel,
                               singleAnim, singleFrame );
        }

        Com_Memset( &mergedHeadEnt, 0, sizeof( mergedHeadEnt ) );
        mergedHeadEnt.reType = RT_MODEL;
        mergedHeadEnt.hModel = s_tpChar.attachments[mergedAttachmentIndex].hModel;
        mergedHeadEnt.renderfx = ent.renderfx;
        VectorCopy( ent.origin, mergedHeadEnt.origin );
        VectorCopy( ent.origin, mergedHeadEnt.oldorigin );
        VectorCopy( ent.lightingOrigin, mergedHeadEnt.lightingOrigin );
        VectorCopy( ent.axis[0], mergedHeadEnt.axis[0] );
        VectorCopy( ent.axis[1], mergedHeadEnt.axis[1] );
        VectorCopy( ent.axis[2], mergedHeadEnt.axis[2] );
        hasMergedHeadEnt = qtrue;
    } else {
        if ( useTorsoBlend && re.UpdateXModelPoseBlend && legsAnimHandle ) {
            re.UpdateXModelPoseBlend( s_tpChar.baseModel,
                                      legsAnimHandle, legsAnimFrame,
                                      torsoAnimHandle, torsoAnimFrame,
                                      torsoRootBone );
        } else if ( re.UpdateXModelPose && ( legsAnimHandle || torsoAnimHandle ) ) {
            qhandle_t singleAnim = legsAnimHandle ? legsAnimHandle : torsoAnimHandle;
            float singleFrame = legsAnimHandle ? legsAnimFrame : torsoAnimFrame;
            re.UpdateXModelPose( s_tpChar.baseModel, singleAnim, singleFrame );
        }
    }

    re.AddRefEntityToScene( &ent );
    if ( hasMergedHeadEnt ) {
        re.AddRefEntityToScene( &mergedHeadEnt );
    }
    CL_TP_AddAttachments( &ent, hasMergedHeadEnt ? &mergedHeadEnt : NULL, mergedAttachmentIndex );
}

void CL_CharacterCod1_Init( void )
{
    cl_drawThirdPersonCharacter = Cvar_Get( "cl_drawThirdPersonCharacter", "1", CVAR_ARCHIVE );
    cl_thirdPersonCharacter     = Cvar_Get( "cl_thirdPersonCharacter", "mp_german_wehrmacht01", CVAR_ARCHIVE );
    cl_thirdPersonModel         = Cvar_Get( "cl_thirdPersonModel", "", CVAR_ARCHIVE );
    cl_thirdPersonYawOffset     = Cvar_Get( "cl_thirdPersonYawOffset", "0", CVAR_ARCHIVE );
    cl_thirdPersonPitchScale    = Cvar_Get( "cl_thirdPersonPitchScale", "0", CVAR_ARCHIVE );
    cl_thirdPersonZOffset       = Cvar_Get( "cl_thirdPersonZOffset", "0", CVAR_ARCHIVE );
    cl_thirdPersonAnimRate      = Cvar_Get( "cl_thirdPersonAnimRate", "1", CVAR_ARCHIVE );
    cl_thirdPersonMoveThreshold = Cvar_Get( "cl_thirdPersonMoveThreshold", "20", CVAR_ARCHIVE );
    cl_thirdPersonFaceView      = Cvar_Get( "cl_thirdPersonFaceView", "0", CVAR_ARCHIVE );
    cl_thirdPersonFaceMove      = Cvar_Get( "cl_thirdPersonFaceMove", "1", CVAR_ARCHIVE );
    cl_thirdPersonUseGsc        = Cvar_Get( "cl_thirdPersonUseGsc", "1", CVAR_ARCHIVE );
    cl_thirdPersonBlendTorso    = Cvar_Get( "cl_thirdPersonBlendTorso", "1", CVAR_ARCHIVE );
    cl_thirdPersonTorsoRoot     = Cvar_Get( "cl_thirdPersonTorsoRoot", "bip01 spine2", CVAR_ARCHIVE );
    cl_thirdPersonYawLerpSpeed  = Cvar_Get( "cl_thirdPersonYawLerpSpeed", "540", CVAR_ARCHIVE );
    cl_thirdPersonDebug         = Cvar_Get( "cl_thirdPersonDebug", "0", CVAR_TEMP );

    Com_Memset( &s_tpChar, 0, sizeof( s_tpChar ) );
    s_tpChar.currentLegAnim = TP_LEG_ANIM_STAND_IDLE;
    s_tpChar.currentTorsoAnim = TP_TORSO_ANIM_STAND_IDLE;
    s_tpChar.legAnimStartTime = cl.serverTime;
    s_tpChar.torsoAnimStartTime = cl.serverTime;

    if ( cl_thirdPersonModel ) {
        cl_thirdPersonModel->modified = qtrue;
    }
    if ( cl_thirdPersonCharacter ) {
        cl_thirdPersonCharacter->modified = qtrue;
    }
    if ( cl_thirdPersonUseGsc ) {
        cl_thirdPersonUseGsc->modified = qtrue;
    }
}

void CL_CharacterCod1_Shutdown( void )
{
    Com_Memset( &s_tpChar, 0, sizeof( s_tpChar ) );
}

#endif /* STANDALONE */
