/*
===========================================================================
cl_character_cod1.c  --  Client-side CoD1 third-person character rendering

Draws a CoD-style xmodel for the local player when cg_thirdPerson is enabled.
Model source:
  1) cl_thirdPersonModel (explicit xmodel path or short name)
  2) character script (cl_thirdPersonCharacter, parsed for setModel/attach)

Animation source:
  CoD MP locomotion xanims (pb_*), selected from playerState legs/torso anim
  state + movement direction.
===========================================================================
*/
#include "client.h"

#ifdef STANDALONE

#include <math.h>

#define TP_MAX_ATTACHMENTS 32
#define TP_TAGNAME_LEN     64

typedef enum {
    TP_ANIM_STAND_IDLE = 0,
    TP_ANIM_STAND_FWD,
    TP_ANIM_STAND_BACK,
    TP_ANIM_STAND_LEFT,
    TP_ANIM_STAND_RIGHT,
    TP_ANIM_CROUCH_IDLE,
    TP_ANIM_CROUCH_FWD,
    TP_ANIM_CROUCH_BACK,
    TP_ANIM_CROUCH_LEFT,
    TP_ANIM_CROUCH_RIGHT,
    TP_ANIM_PRONE_IDLE,
    TP_ANIM_PRONE_FWD,
    TP_ANIM_PRONE_BACK,
    TP_ANIM_PRONE_LEFT,
    TP_ANIM_PRONE_RIGHT,
    TP_ANIM_COUNT
} tpAnimSlot_t;

static const char *s_tpAnimNames[TP_ANIM_COUNT] = {
    "pb_stand_alert",
    "pb_stand_shoot_walk_forward",
    "pb_stand_shoot_walk_back",
    "pb_stand_shoot_walk_left",
    "pb_stand_shoot_walk_right",
    "pb_crouch_alert",
    "pb_crouch_run_forward",
    "pb_crouch_run_back",
    "pb_crouch_run_left",
    "pb_crouch_run_right",
    "pb_prone_aim",
    "pb_prone_crawl",
    "pb_prone_crawl_back",
    "pb_prone_crawl_left",
    "pb_prone_crawl_right"
};

typedef struct {
    char      modelPath[MAX_QPATH];
    char      tagName[TP_TAGNAME_LEN];
    qhandle_t hModel;
} tpAttachment_t;

typedef struct {
    qhandle_t      baseModel;
    qhandle_t      anims[TP_ANIM_COUNT];
    tpAttachment_t attachments[TP_MAX_ATTACHMENTS];
    int            numAttachments;

    char           loadedModelPath[MAX_QPATH];
    char           loadedScriptPath[MAX_QPATH];
    char           loadedModelOverride[MAX_QPATH];

    tpAnimSlot_t   currentAnim;
    int            animStartTime;
    int            lastLegsAnimRaw;
    int            lastTorsoAnimRaw;
    float          renderYaw;
    qboolean       renderYawValid;
} tpCharacterState_t;

static tpCharacterState_t s_tpChar;

/* cvars */
static cvar_t *cl_drawThirdPersonCharacter;
static cvar_t *cl_thirdPersonCharacter;
static cvar_t *cl_thirdPersonModel;
static cvar_t *cl_thirdPersonYawOffset;
static cvar_t *cl_thirdPersonPitchScale;
static cvar_t *cl_thirdPersonZOffset;
static cvar_t *cl_thirdPersonAnimRate;
static cvar_t *cl_thirdPersonMoveThreshold;
static cvar_t *cl_thirdPersonFaceView;
static cvar_t *cl_thirdPersonFaceMove;
static cvar_t *cl_thirdPersonYawLerpSpeed;
static cvar_t *cl_thirdPersonDebug;

static qhandle_t CL_TP_RegisterModelWithFallback( const char *requestedPath,
                                                  char *resolvedPath,
                                                  int resolvedPathSize )
{
    qhandle_t hModel;
    int i;
    const char *fallbacks[] = {
        "xmodel/playerbody_default",
        "xmodel/playerbody_german_wehrmacht",
        "xmodel/playerbody_american_airborne",
        "xmodel/playerbody_russian_veteran"
    };

    if ( !requestedPath || !requestedPath[0] ) {
        resolvedPath[0] = '\0';
        return 0;
    }

    hModel = re.RegisterModel( requestedPath );
    if ( hModel ) {
        Q_strncpyz( resolvedPath, requestedPath, resolvedPathSize );
        return hModel;
    }

    /* CoD1 MP's autogenerated mp_axis_default.gsc references this alias,
     * but many installs only ship playerbody_default. */
    if ( !Q_stricmp( requestedPath, "xmodel/axis_default" ) ) {
        hModel = re.RegisterModel( "xmodel/playerbody_default" );
        if ( hModel ) {
            Q_strncpyz( resolvedPath, "xmodel/playerbody_default", resolvedPathSize );
            return hModel;
        }
    }

    for ( i = 0; i < (int)ARRAY_LEN( fallbacks ); ++i ) {
        if ( !Q_stricmp( requestedPath, fallbacks[i] ) ) {
            continue;
        }

        hModel = re.RegisterModel( fallbacks[i] );
        if ( hModel ) {
            Q_strncpyz( resolvedPath, fallbacks[i], resolvedPathSize );
            return hModel;
        }
    }

    Q_strncpyz( resolvedPath, requestedPath, resolvedPathSize );
    return 0;
}

static void CL_TP_NormalizeModelPath( const char *input, char *out, int outSize )
{
    if ( !input || !input[0] ) {
        out[0] = '\0';
        return;
    }

    if ( Q_strncmp( input, "xmodel/", 7 ) == 0 ) {
        Q_strncpyz( out, input, outSize );
    } else {
        Com_sprintf( out, outSize, "xmodel/%s", input );
    }
}

static void CL_TP_BuildCharacterScriptPath( const char *name, char *outPath, int outSize )
{
    const char *base;

    base = ( name && name[0] ) ? name : "mp_axis_default";

    if ( Q_strncmp( base, "character/", 10 ) == 0 ) {
        Q_strncpyz( outPath, base, outSize );
    } else {
        Com_sprintf( outPath, outSize, "character/%s", base );
    }

    if ( !COM_GetExtension( outPath )[0] ) {
        Q_strcat( outPath, outSize, ".gsc" );
    }
}

static qboolean CL_TP_ParseQuoted( const char *start, const char **after, char *out, int outSize )
{
    const char *open;
    const char *close;
    int len;

    open = strchr( start, '"' );
    if ( !open ) {
        return qfalse;
    }

    close = strchr( open + 1, '"' );
    if ( !close ) {
        return qfalse;
    }

    len = (int)( close - ( open + 1 ) );
    if ( len >= outSize ) {
        len = outSize - 1;
    }

    if ( len > 0 ) {
        memcpy( out, open + 1, len );
    }
    out[len] = '\0';

    if ( after ) {
        *after = close + 1;
    }

    return qtrue;
}

static qboolean CL_TP_IsAliasChar( char c )
{
    return ( ( c >= 'a' && c <= 'z' ) ||
             ( c >= 'A' && c <= 'Z' ) ||
             ( c >= '0' && c <= '9' ) ||
             c == '_' );
}

static qboolean CL_TP_ParseAliasName( const char *text, char *outAlias, int outAliasSize )
{
    const char *marker;
    int i;

    marker = Q_stristr( text, "xmodelalias\\" );
    if ( !marker ) {
        marker = Q_stristr( text, "xmodelalias/" );
    }
    if ( !marker ) {
        return qfalse;
    }

    marker += 11; /* strlen("xmodelalias/") */
    i = 0;
    while ( marker[i] && CL_TP_IsAliasChar( marker[i] ) ) {
        if ( i >= outAliasSize - 1 ) {
            break;
        }
        outAlias[i] = marker[i];
        i++;
    }

    if ( i <= 0 ) {
        return qfalse;
    }

    outAlias[i] = '\0';
    return qtrue;
}

static qboolean CL_TP_ResolveAliasToModel( const char *text, char *outModelPath, int outModelPathSize )
{
    char aliasName[MAX_QPATH];
    char aliasPath[MAX_QPATH];
    char *aliasText;
    long aliasLen;
    const char *scan;

    outModelPath[0] = '\0';

    if ( !CL_TP_ParseAliasName( text, aliasName, sizeof( aliasName ) ) ) {
        return qfalse;
    }

    Com_sprintf( aliasPath, sizeof( aliasPath ), "xmodelalias/%s.gsc", aliasName );
    aliasText = NULL;
    aliasLen = FS_ReadFile( aliasPath, (void **)&aliasText );
    if ( aliasLen <= 0 || !aliasText ) {
        return qfalse;
    }

    scan = aliasText;
    while ( CL_TP_ParseQuoted( scan, &scan, outModelPath, outModelPathSize ) ) {
        if ( outModelPath[0] ) {
            CL_TP_NormalizeModelPath( outModelPath, outModelPath, outModelPathSize );
            FS_FreeFile( aliasText );
            return qtrue;
        }
    }

    FS_FreeFile( aliasText );
    outModelPath[0] = '\0';
    return qfalse;
}

static qboolean CL_TP_IsHeadLikeModel( const char *modelPath )
{
    return modelPath && (
        Q_stristr( modelPath, "basehead" ) ||
        Q_stristr( modelPath, "head_" ) ||
        Q_stristr( modelPath, "/head" ) ||
        Q_stristr( modelPath, "headaxis" )
    );
}

static qboolean CL_TP_IsHelmetLikeModel( const char *modelPath )
{
    return modelPath && (
        Q_stristr( modelPath, "helmet" ) ||
        Q_stristr( modelPath, "_hat" ) ||
        Q_stristr( modelPath, "hat_" ) ||
        Q_stristr( modelPath, "sidecap" ) ||
        Q_stristr( modelPath, "officercap" ) ||
        Q_stristr( modelPath, "_cap" ) ||
        Q_stristr( modelPath, "cap_" )
    );
}

static const char *CL_TP_DefaultTagForAttachment( const char *modelPath )
{
    if ( CL_TP_IsHeadLikeModel( modelPath ) ) {
        return "bip01 head";
    }

    if ( CL_TP_IsHelmetLikeModel( modelPath ) ) {
        return "tag_helmet";
    }

    return "";
}

static void CL_TP_AddAttachment( tpAttachment_t *attachments, int *numAttachments,
                                 const char *modelPath, const char *tagName )
{
    int i;

    if ( !modelPath || !modelPath[0] ) {
        return;
    }

    for ( i = 0; i < *numAttachments; ++i ) {
        if ( !Q_stricmp( attachments[i].modelPath, modelPath ) &&
             !Q_stricmp( attachments[i].tagName, tagName ? tagName : "" ) ) {
            return;
        }
    }

    if ( *numAttachments >= TP_MAX_ATTACHMENTS ) {
        return;
    }

    Q_strncpyz( attachments[*numAttachments].modelPath, modelPath,
                sizeof( attachments[*numAttachments].modelPath ) );
    Q_strncpyz( attachments[*numAttachments].tagName,
                tagName ? tagName : "",
                sizeof( attachments[*numAttachments].tagName ) );
    attachments[*numAttachments].hModel = 0;
    ( *numAttachments )++;
}

static qboolean CL_TP_ParseCharacterScript( const char *scriptPath,
                                            char *outBaseModel,
                                            tpAttachment_t *outAttachments,
                                            int *outNumAttachments )
{
    char *fileText;
    long fileLen;
    const char *scan;
    char hatModel[MAX_QPATH];
    qboolean foundBaseModel;

    *outNumAttachments = 0;
    outBaseModel[0] = '\0';
    hatModel[0] = '\0';
    foundBaseModel = qfalse;

    fileText = NULL;
    fileLen = FS_ReadFile( scriptPath, (void **)&fileText );
    if ( fileLen <= 0 || !fileText ) {
        return qfalse;
    }

    scan = fileText;
    while ( ( scan = Q_stristr( scan, "setModel(" ) ) != NULL ) {
        char modelRaw[MAX_QPATH];
        char modelPath[MAX_QPATH];

        if ( CL_TP_ParseQuoted( scan, NULL, modelRaw, sizeof( modelRaw ) ) ) {
            CL_TP_NormalizeModelPath( modelRaw, modelPath, sizeof( modelPath ) );
            Q_strncpyz( outBaseModel, modelPath, MAX_QPATH );
            foundBaseModel = qtrue;
            break;
        }

        scan += 9;
    }

    if ( !foundBaseModel ) {
        scan = fileText;
        while ( ( scan = Q_stristr( scan, "setModelFromArray(" ) ) != NULL ) {
            const char *open;
            const char *close;
            char args[512];
            int argsLen;
            char modelPath[MAX_QPATH];

            open = strchr( scan, '(' );
            close = open ? strchr( open, ')' ) : NULL;
            if ( !open || !close || close <= open + 1 ) {
                scan += 17;
                continue;
            }

            argsLen = (int)( close - ( open + 1 ) );
            if ( argsLen >= (int)sizeof( args ) ) {
                argsLen = sizeof( args ) - 1;
            }

            memcpy( args, open + 1, argsLen );
            args[argsLen] = '\0';

            if ( CL_TP_ResolveAliasToModel( args, modelPath, sizeof( modelPath ) ) ) {
                Q_strncpyz( outBaseModel, modelPath, MAX_QPATH );
                foundBaseModel = qtrue;
                break;
            }

            scan = close + 1;
        }
    }

    scan = fileText;
    while ( ( scan = Q_stristr( scan, "self.hatModel" ) ) != NULL ) {
        const char *eq;
        const char *semi;
        char modelRaw[MAX_QPATH];
        char modelPath[MAX_QPATH];
        char expr[512];
        int exprLen;

        eq = strchr( scan, '=' );
        semi = strchr( scan, ';' );
        if ( !eq || ( semi && eq > semi ) ) {
            scan += 13;
            continue;
        }

        if ( CL_TP_ParseQuoted( eq + 1, NULL, modelRaw, sizeof( modelRaw ) ) ) {
            CL_TP_NormalizeModelPath( modelRaw, modelPath, sizeof( modelPath ) );
            Q_strncpyz( hatModel, modelPath, sizeof( hatModel ) );
            break;
        }

        exprLen = semi ? (int)( semi - ( eq + 1 ) ) : (int)strlen( eq + 1 );
        if ( exprLen >= (int)sizeof( expr ) ) {
            exprLen = sizeof( expr ) - 1;
        }
        if ( exprLen > 0 ) {
            memcpy( expr, eq + 1, exprLen );
        }
        expr[exprLen] = '\0';
        if ( CL_TP_ResolveAliasToModel( expr, modelPath, sizeof( modelPath ) ) ) {
            Q_strncpyz( hatModel, modelPath, sizeof( hatModel ) );
            break;
        }

        scan += 13;
    }

    scan = fileText;
    while ( ( scan = Q_stristr( scan, "attachFromArray(" ) ) != NULL &&
            *outNumAttachments < TP_MAX_ATTACHMENTS ) {
        const char *open;
        const char *close;
        char args[512];
        int argsLen;
        char attachModelPath[MAX_QPATH];
        const char *defaultTag;

        open = strchr( scan, '(' );
        close = open ? strchr( open, ')' ) : NULL;
        if ( !open || !close || close <= open + 1 ) {
            scan += 16;
            continue;
        }

        argsLen = (int)( close - ( open + 1 ) );
        if ( argsLen >= (int)sizeof( args ) ) {
            argsLen = sizeof( args ) - 1;
        }

        memcpy( args, open + 1, argsLen );
        args[argsLen] = '\0';

        if ( CL_TP_ResolveAliasToModel( args, attachModelPath, sizeof( attachModelPath ) ) ) {
            defaultTag = CL_TP_DefaultTagForAttachment( attachModelPath );
            if ( defaultTag[0] ) {
                CL_TP_AddAttachment( outAttachments, outNumAttachments,
                                     attachModelPath, defaultTag );
            }
        }

        scan = close + 1;
    }

    scan = fileText;
    while ( ( scan = Q_stristr( scan, "attach(" ) ) != NULL &&
            *outNumAttachments < TP_MAX_ATTACHMENTS ) {
        const char *open;
        const char *close;
        char args[512];
        int argsLen;
        char attachModelRaw[MAX_QPATH];
        char attachModelPath[MAX_QPATH];
        char attachTag[TP_TAGNAME_LEN];
        const char *afterFirst;

        open = strchr( scan, '(' );
        close = open ? strchr( open, ')' ) : NULL;
        if ( !open || !close || close <= open + 1 ) {
            scan += 7;
            continue;
        }

        argsLen = (int)( close - ( open + 1 ) );
        if ( argsLen >= (int)sizeof( args ) ) {
            argsLen = sizeof( args ) - 1;
        }

        memcpy( args, open + 1, argsLen );
        args[argsLen] = '\0';

        attachModelPath[0] = '\0';
        attachTag[0] = '\0';

        if ( Q_stristr( args, "self.hatModel" ) && hatModel[0] ) {
            Q_strncpyz( attachModelPath, hatModel, sizeof( attachModelPath ) );
        } else if ( CL_TP_ParseQuoted( args, &afterFirst, attachModelRaw,
                                        sizeof( attachModelRaw ) ) ) {
            CL_TP_NormalizeModelPath( attachModelRaw, attachModelPath,
                                      sizeof( attachModelPath ) );

            if ( CL_TP_ParseQuoted( afterFirst, NULL, attachTag,
                                    sizeof( attachTag ) ) ) {
                /* Keep explicit tag if present, including TAG_* bones. */
            }
        }

        if ( attachModelPath[0] && !attachTag[0] ) {
            const char *defaultTag = CL_TP_DefaultTagForAttachment( attachModelPath );
            if ( defaultTag[0] ) {
                Q_strncpyz( attachTag, defaultTag, sizeof( attachTag ) );
            } else {
                /* Many empty-tag gear models expect full bone-merge.
                 * Skip those for now to avoid floating gear. */
                scan = close + 1;
                continue;
            }
        }

        CL_TP_AddAttachment( outAttachments, outNumAttachments,
                             attachModelPath, attachTag );
        scan = close + 1;
    }

    FS_FreeFile( fileText );
    return foundBaseModel;
}

static void CL_TP_LoadAnimations( void )
{
    int i;

    for ( i = 0; i < TP_ANIM_COUNT; ++i ) {
        s_tpChar.anims[i] = 0;
        if ( re.RegisterXAnim ) {
            s_tpChar.anims[i] = re.RegisterXAnim( s_tpAnimNames[i] );
        }

        if ( !s_tpChar.anims[i] && cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
            Com_Printf( "thirdperson: missing xanim '%s'\n", s_tpAnimNames[i] );
        }
    }

    s_tpChar.currentAnim = TP_ANIM_STAND_IDLE;
    s_tpChar.animStartTime = cl.serverTime;
    s_tpChar.lastLegsAnimRaw = -1;
    s_tpChar.lastTorsoAnimRaw = -1;
}

static qboolean CL_TP_AttachmentListsEqual( const tpAttachment_t *a, int aCount,
                                            const tpAttachment_t *b, int bCount )
{
    int i;

    if ( aCount != bCount ) {
        return qfalse;
    }

    for ( i = 0; i < aCount; ++i ) {
        if ( Q_stricmp( a[i].modelPath, b[i].modelPath ) ||
             Q_stricmp( a[i].tagName, b[i].tagName ) ) {
            return qfalse;
        }
    }

    return qtrue;
}

static void CL_TP_LoadCharacterAssets( void )
{
    char desiredModelPath[MAX_QPATH];
    char desiredScriptPath[MAX_QPATH];
    tpAttachment_t desiredAttachments[TP_MAX_ATTACHMENTS];
    int desiredAttachmentCount;
    qboolean fromScript;
    int i;

    desiredModelPath[0] = '\0';
    desiredScriptPath[0] = '\0';
    desiredAttachmentCount = 0;
    fromScript = qfalse;

    if ( cl_thirdPersonModel && cl_thirdPersonModel->string[0] ) {
        CL_TP_NormalizeModelPath( cl_thirdPersonModel->string,
                                  desiredModelPath, sizeof( desiredModelPath ) );
    } else {
        CL_TP_BuildCharacterScriptPath( cl_thirdPersonCharacter ? cl_thirdPersonCharacter->string : "",
                                        desiredScriptPath, sizeof( desiredScriptPath ) );
        fromScript = CL_TP_ParseCharacterScript( desiredScriptPath,
                                                 desiredModelPath,
                                                 desiredAttachments,
                                                 &desiredAttachmentCount );
    }

    if ( !desiredModelPath[0] ) {
        CL_TP_NormalizeModelPath( "axis_default", desiredModelPath,
                                  sizeof( desiredModelPath ) );
    }

    if ( s_tpChar.baseModel &&
         !Q_stricmp( s_tpChar.loadedModelPath, desiredModelPath ) &&
         !Q_stricmp( s_tpChar.loadedScriptPath, desiredScriptPath ) &&
         !Q_stricmp( s_tpChar.loadedModelOverride,
                    cl_thirdPersonModel ? cl_thirdPersonModel->string : "" ) &&
         CL_TP_AttachmentListsEqual( s_tpChar.attachments, s_tpChar.numAttachments,
                                     desiredAttachments, desiredAttachmentCount ) ) {
        return;
    }

    Com_Memset( &s_tpChar.attachments, 0, sizeof( s_tpChar.attachments ) );
    s_tpChar.numAttachments = 0;

    s_tpChar.baseModel = CL_TP_RegisterModelWithFallback( desiredModelPath,
                                                          desiredModelPath,
                                                          sizeof( desiredModelPath ) );

    if ( !s_tpChar.baseModel ) {
        Com_Printf( "thirdperson: failed to load model '%s' (and fallback playerbody models)\n",
                    desiredModelPath );
    }

    for ( i = 0; i < desiredAttachmentCount; ++i ) {
        s_tpChar.attachments[s_tpChar.numAttachments] = desiredAttachments[i];
        s_tpChar.attachments[s_tpChar.numAttachments].hModel =
            re.RegisterModel( s_tpChar.attachments[s_tpChar.numAttachments].modelPath );

        if ( !s_tpChar.attachments[s_tpChar.numAttachments].hModel &&
             cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
            Com_Printf( "thirdperson: missing attachment '%s'\n",
                        s_tpChar.attachments[s_tpChar.numAttachments].modelPath );
        }

        s_tpChar.numAttachments++;
    }

    Q_strncpyz( s_tpChar.loadedModelPath, desiredModelPath, sizeof( s_tpChar.loadedModelPath ) );
    Q_strncpyz( s_tpChar.loadedScriptPath, desiredScriptPath, sizeof( s_tpChar.loadedScriptPath ) );
    Q_strncpyz( s_tpChar.loadedModelOverride,
                cl_thirdPersonModel ? cl_thirdPersonModel->string : "",
                sizeof( s_tpChar.loadedModelOverride ) );

    if ( cl_thirdPersonDebug && cl_thirdPersonDebug->integer ) {
        if ( fromScript ) {
            Com_Printf( "thirdperson: script '%s' -> model '%s' (%d attachments)\n",
                        desiredScriptPath, desiredModelPath, s_tpChar.numAttachments );
        } else {
            Com_Printf( "thirdperson: override model '%s' (%d attachments)\n",
                        desiredModelPath, s_tpChar.numAttachments );
        }
    }
}

static float CL_TP_GetSnapshotLerpFrac( const clSnapshot_t **outPrevSnap )
{
    const clSnapshot_t *prevSnap;
    int prevMsgNum;
    int denom;
    float frac;

    *outPrevSnap = NULL;

    prevMsgNum = cl.snap.messageNum - 1;
    if ( prevMsgNum < 0 ) {
        return 1.0f;
    }

    prevSnap = &cl.snapshots[prevMsgNum & PACKET_MASK];
    if ( !prevSnap->valid || prevSnap->messageNum != prevMsgNum ) {
        return 1.0f;
    }

    denom = cl.snap.serverTime - prevSnap->serverTime;
    if ( denom <= 0 ) {
        return 1.0f;
    }

    frac = (float)( cl.serverTime - prevSnap->serverTime ) / (float)denom;
    if ( frac < 0.0f ) {
        frac = 0.0f;
    } else if ( frac > 1.0f ) {
        frac = 1.0f;
    }

    *outPrevSnap = prevSnap;
    return frac;
}

static void CL_TP_GetInterpolatedState( vec3_t outOrigin, vec3_t outVelocity, int *outViewHeight )
{
    const clSnapshot_t *prevSnap;
    float frac;
    int i;

    frac = CL_TP_GetSnapshotLerpFrac( &prevSnap );
    if ( !prevSnap ) {
        VectorCopy( cl.snap.ps.origin, outOrigin );
        VectorCopy( cl.snap.ps.velocity, outVelocity );
        *outViewHeight = cl.snap.ps.viewheight;
        return;
    }

    for ( i = 0; i < 3; ++i ) {
        outOrigin[i] = prevSnap->ps.origin[i] +
                       frac * ( cl.snap.ps.origin[i] - prevSnap->ps.origin[i] );
        outVelocity[i] = prevSnap->ps.velocity[i] +
                         frac * ( cl.snap.ps.velocity[i] - prevSnap->ps.velocity[i] );
    }

    *outViewHeight = (int)( prevSnap->ps.viewheight +
                            frac * (float)( cl.snap.ps.viewheight - prevSnap->ps.viewheight ) );
}

static float CL_TP_StepYawToward( float currentYaw, float desiredYaw, float maxStep )
{
    float delta;

    delta = AngleSubtract( desiredYaw, currentYaw );
    if ( delta > maxStep ) {
        delta = maxStep;
    } else if ( delta < -maxStep ) {
        delta = -maxStep;
    }

    return AngleNormalize360( currentYaw + delta );
}

static tpAnimSlot_t CL_TP_IdleAnimForStance( qboolean crouched, qboolean prone )
{
    if ( prone ) {
        return TP_ANIM_PRONE_IDLE;
    }
    if ( crouched ) {
        return TP_ANIM_CROUCH_IDLE;
    }
    return TP_ANIM_STAND_IDLE;
}

static tpAnimSlot_t CL_TP_MoveAnimForDir( int dir, qboolean crouched, qboolean prone, qboolean forceBack )
{
    if ( forceBack ) {
        dir = 4;
    }

    if ( prone ) {
        switch ( dir ) {
            case 4:
            case 3:
            case 5:
                return TP_ANIM_PRONE_BACK;
            case 2:
                return TP_ANIM_PRONE_LEFT;
            case 6:
                return TP_ANIM_PRONE_RIGHT;
            default:
                return TP_ANIM_PRONE_FWD;
        }
    }

    if ( crouched ) {
        switch ( dir ) {
            case 4:
            case 3:
            case 5:
                return TP_ANIM_CROUCH_BACK;
            case 2:
                return TP_ANIM_CROUCH_LEFT;
            case 6:
                return TP_ANIM_CROUCH_RIGHT;
            default:
                return TP_ANIM_CROUCH_FWD;
        }
    }

    switch ( dir ) {
        case 4:
        case 3:
        case 5:
            return TP_ANIM_STAND_BACK;
        case 2:
            return TP_ANIM_STAND_LEFT;
        case 6:
            return TP_ANIM_STAND_RIGHT;
        default:
            return TP_ANIM_STAND_FWD;
    }
}

static tpAnimSlot_t CL_TP_ChooseAnimForPlayerState( const playerState_t *ps )
{
    int legsAnim;
    int torsoAnim;
    float xyspeed;
    qboolean moving;
    qboolean crouched;
    qboolean prone;
    qboolean forceBack;
    int dir;

    legsAnim = ps->legsAnim & ~ANIM_TOGGLEBIT;
    torsoAnim = ps->torsoAnim & ~ANIM_TOGGLEBIT;

    xyspeed = sqrtf( ps->velocity[0] * ps->velocity[0] +
                     ps->velocity[1] * ps->velocity[1] );
    moving = qfalse;
    crouched = ( ps->pm_flags & PMF_DUCKED ) ? qtrue : qfalse;
    prone = ( ps->viewheight <= ( PRONE_VIEWHEIGHT + 1 ) );
    forceBack = qfalse;
    dir = ps->movementDir & 7;

    if ( ps->pm_type != PM_NORMAL && ps->pm_type != PM_DEAD ) {
        return CL_TP_IdleAnimForStance( crouched, prone );
    }

    switch ( legsAnim ) {
        case LEGS_WALKCR:
            crouched = qtrue;
            moving = qtrue;
            break;
        case LEGS_IDLECR:
            crouched = qtrue;
            moving = qfalse;
            break;
        case LEGS_BACKCR:
            crouched = qtrue;
            moving = qtrue;
            forceBack = qtrue;
            break;
        case LEGS_WALK:
        case LEGS_RUN:
        case LEGS_SWIM:
        case LEGS_JUMP:
        case LEGS_LAND:
        case LEGS_JUMPB:
        case LEGS_LANDB:
            moving = qtrue;
            break;
        case LEGS_BACK:
        case LEGS_BACKWALK:
            moving = qtrue;
            forceBack = qtrue;
            break;
        default:
            moving = qfalse;
            break;
    }

    if ( !moving ) {
        moving = ( xyspeed > ( cl_thirdPersonMoveThreshold ? cl_thirdPersonMoveThreshold->value : 20.0f ) );
    }

    if ( torsoAnim == TORSO_ATTACK || torsoAnim == TORSO_ATTACK2 ) {
        if ( ps->groundEntityNum != ENTITYNUM_NONE ) {
            moving = qtrue;
        }
    }

    if ( !moving || ps->groundEntityNum == ENTITYNUM_NONE ) {
        return CL_TP_IdleAnimForStance( crouched, prone );
    }

    return CL_TP_MoveAnimForDir( dir, crouched, prone, forceBack );
}

static qhandle_t CL_TP_GetAnimHandleForState( tpAnimSlot_t slot )
{
    if ( slot < 0 || slot >= TP_ANIM_COUNT ) {
        slot = TP_ANIM_STAND_IDLE;
    }

    if ( s_tpChar.anims[slot] ) {
        return s_tpChar.anims[slot];
    }

    return s_tpChar.anims[TP_ANIM_STAND_IDLE];
}

static float CL_TP_ComputeAnimFrame( qhandle_t animHandle )
{
    int fps;
    int numFrames;
    float elapsed;
    float frame;
    float rate;

    if ( !animHandle ) {
        return 0.0f;
    }

    fps = re.XAnimFramerate ? re.XAnimFramerate( animHandle ) : 30;
    numFrames = re.XAnimNumFrames ? re.XAnimNumFrames( animHandle ) : 1;

    if ( fps <= 0 ) {
        fps = 30;
    }
    if ( numFrames <= 0 ) {
        numFrames = 1;
    }

    rate = cl_thirdPersonAnimRate ? cl_thirdPersonAnimRate->value : 1.0f;
    if ( rate <= 0.0f ) {
        rate = 1.0f;
    }

    elapsed = (float)( cl.serverTime - s_tpChar.animStartTime ) * 0.001f;
    frame = elapsed * (float)fps * rate;

    if ( numFrames > 1 ) {
        frame = fmodf( frame, (float)numFrames );
    } else {
        frame = 0.0f;
    }

    return frame;
}

static qboolean CL_TP_PositionOnTag( refEntity_t *ent, const refEntity_t *parent,
                                     const char *tagName )
{
    orientation_t tag;
    vec3_t origin;
    vec3_t parentAxis[3];

    if ( !tagName || !tagName[0] ) {
        return qfalse;
    }

    if ( !re.LerpTag( &tag, parent->hModel, 0, 0, 1.0f, tagName ) ) {
        return qfalse;
    }

    VectorCopy( parent->origin, origin );
    VectorMA( origin, tag.origin[0], parent->axis[0], origin );
    VectorMA( origin, tag.origin[1], parent->axis[1], origin );
    VectorMA( origin, tag.origin[2], parent->axis[2], origin );

    VectorCopy( origin, ent->origin );
    VectorCopy( origin, ent->oldorigin );

    VectorCopy( parent->axis[0], parentAxis[0] );
    VectorCopy( parent->axis[1], parentAxis[1] );
    VectorCopy( parent->axis[2], parentAxis[2] );
    MatrixMultiply( tag.axis, parentAxis, ent->axis );

    return qtrue;
}

static void CL_TP_PositionAttachment( refEntity_t *ent, const refEntity_t *parent,
                                      const tpAttachment_t *attachment )
{
    static const char *headFallbackTags[] = {
        "bip01 spine2", "bip01 neck", "neck", "bip01 head", "head", "tag_helmet"
    };
    static const char *helmetFallbackTags[] = {
        "tag_helmet", "bip01 head", "head"
    };
    int i;

    if ( attachment->tagName[0] &&
         CL_TP_PositionOnTag( ent, parent, attachment->tagName ) ) {
        return;
    }

    if ( CL_TP_IsHeadLikeModel( attachment->modelPath ) ) {
        for ( i = 0; i < (int)ARRAY_LEN( headFallbackTags ); ++i ) {
            if ( CL_TP_PositionOnTag( ent, parent, headFallbackTags[i] ) ) {
                return;
            }
        }
    } else if ( CL_TP_IsHelmetLikeModel( attachment->modelPath ) ) {
        for ( i = 0; i < (int)ARRAY_LEN( helmetFallbackTags ); ++i ) {
            if ( CL_TP_PositionOnTag( ent, parent, helmetFallbackTags[i] ) ) {
                return;
            }
        }
    }
}

static void CL_TP_AddAttachments( const refEntity_t *baseEnt )
{
    int i;

    for ( i = 0; i < s_tpChar.numAttachments; ++i ) {
        refEntity_t att;

        if ( !s_tpChar.attachments[i].hModel ) {
            continue;
        }

        Com_Memset( &att, 0, sizeof( att ) );
        att.reType = RT_MODEL;
        att.hModel = s_tpChar.attachments[i].hModel;
        att.renderfx = baseEnt->renderfx;

        VectorCopy( baseEnt->origin, att.origin );
        VectorCopy( baseEnt->origin, att.oldorigin );
        VectorCopy( baseEnt->lightingOrigin, att.lightingOrigin );
        VectorCopy( baseEnt->axis[0], att.axis[0] );
        VectorCopy( baseEnt->axis[1], att.axis[1] );
        VectorCopy( baseEnt->axis[2], att.axis[2] );

        CL_TP_PositionAttachment( &att, baseEnt, &s_tpChar.attachments[i] );

        re.AddRefEntityToScene( &att );
    }
}

static void CL_TP_EnsureAssets( void )
{
    if ( !s_tpChar.anims[TP_ANIM_STAND_IDLE] ) {
        CL_TP_LoadAnimations();
    }

    if ( !s_tpChar.baseModel ||
         ( cl_thirdPersonModel && cl_thirdPersonModel->modified ) ||
         ( cl_thirdPersonCharacter && cl_thirdPersonCharacter->modified ) ) {
        CL_TP_LoadCharacterAssets();

        if ( cl_thirdPersonModel ) {
            cl_thirdPersonModel->modified = qfalse;
        }
        if ( cl_thirdPersonCharacter ) {
            cl_thirdPersonCharacter->modified = qfalse;
        }
    }
}

void CL_AddThirdPersonCharacter( const refdef_t *fd )
{
    refEntity_t ent;
    vec3_t angles;
    vec3_t interpOrigin;
    vec3_t interpVelocity;
    int interpViewHeight;
    float xyspeed;
    float desiredYaw;
    float maxYawStep;
    playerState_t interpPs;
    tpAnimSlot_t desiredAnim;
    int legsAnimRaw;
    int torsoAnimRaw;
    qhandle_t animHandle;
    float animFrame;

    if ( !fd || ( fd->rdflags & RDF_NOWORLDMODEL ) ) {
        return;
    }

    if ( !cl_drawThirdPersonCharacter || !cl_drawThirdPersonCharacter->integer ) {
        return;
    }

    if ( !cl.snap.valid ) {
        return;
    }

    if ( cl.snap.ps.pm_flags & PMF_FOLLOW ) {
        return;
    }

    if ( !Cvar_VariableIntegerValue( "cg_thirdPerson" ) ) {
        return;
    }

    CL_TP_EnsureAssets();

    if ( !s_tpChar.baseModel ) {
        return;
    }

    CL_TP_GetInterpolatedState( interpOrigin, interpVelocity, &interpViewHeight );
    interpPs = cl.snap.ps;
    VectorCopy( interpVelocity, interpPs.velocity );
    interpPs.viewheight = interpViewHeight;

    legsAnimRaw = interpPs.legsAnim;
    torsoAnimRaw = interpPs.torsoAnim;
    desiredAnim = CL_TP_ChooseAnimForPlayerState( &interpPs );
    if ( desiredAnim != s_tpChar.currentAnim ||
         legsAnimRaw != s_tpChar.lastLegsAnimRaw ||
         torsoAnimRaw != s_tpChar.lastTorsoAnimRaw ) {
        s_tpChar.currentAnim = desiredAnim;
        s_tpChar.animStartTime = cl.serverTime;
        s_tpChar.lastLegsAnimRaw = legsAnimRaw;
        s_tpChar.lastTorsoAnimRaw = torsoAnimRaw;
    }

    animHandle = CL_TP_GetAnimHandleForState( s_tpChar.currentAnim );
    animFrame = CL_TP_ComputeAnimFrame( animHandle );

    if ( re.UpdateXModelPose && animHandle ) {
        re.UpdateXModelPose( s_tpChar.baseModel, animHandle, animFrame );
    }

    Com_Memset( &ent, 0, sizeof( ent ) );
    ent.reType = RT_MODEL;
    ent.hModel = s_tpChar.baseModel;
    ent.renderfx = RF_LIGHTING_ORIGIN;

    VectorCopy( interpOrigin, ent.origin );
    ent.origin[2] += cl_thirdPersonZOffset ? cl_thirdPersonZOffset->value : 0.0f;

    VectorCopy( ent.origin, ent.oldorigin );
    VectorCopy( ent.origin, ent.lightingOrigin );

    xyspeed = sqrtf( interpVelocity[0] * interpVelocity[0] +
                     interpVelocity[1] * interpVelocity[1] );
    if ( cl_thirdPersonFaceMove && cl_thirdPersonFaceMove->integer &&
         xyspeed > ( cl_thirdPersonMoveThreshold ? cl_thirdPersonMoveThreshold->value : 20.0f ) &&
         interpPs.groundEntityNum != ENTITYNUM_NONE ) {
        desiredYaw = RAD2DEG( atan2f( interpVelocity[1], interpVelocity[0] ) );
    } else if ( cl_thirdPersonFaceView && cl_thirdPersonFaceView->integer ) {
        desiredYaw = cl.viewangles[YAW];
    } else if ( s_tpChar.renderYawValid ) {
        desiredYaw = s_tpChar.renderYaw;
    } else {
        desiredYaw = cl.viewangles[YAW];
    }

    if ( !s_tpChar.renderYawValid ) {
        s_tpChar.renderYaw = desiredYaw;
        s_tpChar.renderYawValid = qtrue;
    } else {
        maxYawStep = ( cl_thirdPersonYawLerpSpeed ? cl_thirdPersonYawLerpSpeed->value : 540.0f ) *
                     ( (float)cls.frametime * 0.001f );
        if ( maxYawStep < 0.0f ) {
            maxYawStep = 0.0f;
        }
        s_tpChar.renderYaw = CL_TP_StepYawToward( s_tpChar.renderYaw, desiredYaw, maxYawStep );
    }

    VectorClear( angles );
    angles[PITCH] = cl.viewangles[PITCH] * ( cl_thirdPersonPitchScale ? cl_thirdPersonPitchScale->value : 0.0f );
    angles[YAW] = s_tpChar.renderYaw + ( cl_thirdPersonYawOffset ? cl_thirdPersonYawOffset->value : 0.0f );
    AnglesToAxis( angles, ent.axis );

    re.AddRefEntityToScene( &ent );
    CL_TP_AddAttachments( &ent );
}

void CL_CharacterCod1_Init( void )
{
    cl_drawThirdPersonCharacter = Cvar_Get( "cl_drawThirdPersonCharacter", "1", CVAR_ARCHIVE );
    cl_thirdPersonCharacter     = Cvar_Get( "cl_thirdPersonCharacter", "mp_german_wehrmacht01", CVAR_ARCHIVE );
    cl_thirdPersonModel         = Cvar_Get( "cl_thirdPersonModel", "", CVAR_ARCHIVE );
    cl_thirdPersonYawOffset     = Cvar_Get( "cl_thirdPersonYawOffset", "0", CVAR_ARCHIVE );
    cl_thirdPersonPitchScale    = Cvar_Get( "cl_thirdPersonPitchScale", "0", CVAR_ARCHIVE );
    cl_thirdPersonZOffset       = Cvar_Get( "cl_thirdPersonZOffset", "0", CVAR_ARCHIVE );
    cl_thirdPersonAnimRate      = Cvar_Get( "cl_thirdPersonAnimRate", "1", CVAR_ARCHIVE );
    cl_thirdPersonMoveThreshold = Cvar_Get( "cl_thirdPersonMoveThreshold", "20", CVAR_ARCHIVE );
    cl_thirdPersonFaceView      = Cvar_Get( "cl_thirdPersonFaceView", "1", CVAR_ARCHIVE );
    cl_thirdPersonFaceMove      = Cvar_Get( "cl_thirdPersonFaceMove", "0", CVAR_ARCHIVE );
    cl_thirdPersonYawLerpSpeed  = Cvar_Get( "cl_thirdPersonYawLerpSpeed", "540", CVAR_ARCHIVE );
    cl_thirdPersonDebug         = Cvar_Get( "cl_thirdPersonDebug", "0", CVAR_TEMP );

    Com_Memset( &s_tpChar, 0, sizeof( s_tpChar ) );
    s_tpChar.currentAnim = TP_ANIM_STAND_IDLE;
    s_tpChar.animStartTime = cl.serverTime;
    s_tpChar.lastLegsAnimRaw = -1;
    s_tpChar.lastTorsoAnimRaw = -1;

    if ( cl_thirdPersonModel ) {
        cl_thirdPersonModel->modified = qtrue;
    }
    if ( cl_thirdPersonCharacter ) {
        cl_thirdPersonCharacter->modified = qtrue;
    }
}

void CL_CharacterCod1_Shutdown( void )
{
    Com_Memset( &s_tpChar, 0, sizeof( s_tpChar ) );
}

#endif /* STANDALONE */
